/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package softheon.enterprise.api.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The model that is sent in response to a GET request for Drawers.
 */
public class DrawerModel {
    /**
     * Gets or sets the identifier.
     */
    @JsonProperty(value = "ID")
    private Integer id;

    /**
     * Gets or sets the cabinet identifier.
     */
    @JsonProperty(value = "CabinetID")
    private Integer cabinetID;

    /**
     * Gets or sets the user identifier.
     */
    @JsonProperty(value = "UserID")
    private Integer userID;

    /**
     * Gets or sets the full name of the user.
     */
    @JsonProperty(value = "UserFullName")
    private String userFullName;

    /**
     * Gets or sets the name.
     */
    @JsonProperty(value = "Name", required = true)
    private String name;

    /**
     * Gets or sets the edition.
     */
    @JsonProperty(value = "Edition")
    private Integer edition;

    /**
     * Gets or sets the state.
     */
    @JsonProperty(value = "State")
    private Integer state;

    /**
     * Gets or sets the entity feature.
     */
    @JsonProperty(value = "EntityFeature")
    private Integer entityFeature;

    /**
     * Gets or sets the attachment feature.
     */
    @JsonProperty(value = "AttachmentFeature")
    private Integer attachmentFeature;

    /**
     * Gets or sets the note feature.
     */
    @JsonProperty(value = "NoteFeature")
    private Integer noteFeature;

    /**
     * Gets or sets the reserved integer 1.
     */
    @JsonProperty(value = "ReservedInt1")
    private Integer reservedInt1;

    /**
     * Gets or sets the reserved integer 2.
     */
    @JsonProperty(value = "ReservedInt2")
    private Integer reservedInt2;

    /**
     * Gets or sets the reserved string1.
     */
    @JsonProperty(value = "ReservedString1")
    private String reservedString1;

    /**
     * Gets or sets the reserved string2.
     */
    @JsonProperty(value = "ReservedString2")
    private String reservedString2;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public Integer id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the DrawerModel object itself.
     */
    public DrawerModel withId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Get the cabinetID value.
     *
     * @return the cabinetID value
     */
    public Integer cabinetID() {
        return this.cabinetID;
    }

    /**
     * Set the cabinetID value.
     *
     * @param cabinetID the cabinetID value to set
     * @return the DrawerModel object itself.
     */
    public DrawerModel withCabinetID(Integer cabinetID) {
        this.cabinetID = cabinetID;
        return this;
    }

    /**
     * Get the userID value.
     *
     * @return the userID value
     */
    public Integer userID() {
        return this.userID;
    }

    /**
     * Set the userID value.
     *
     * @param userID the userID value to set
     * @return the DrawerModel object itself.
     */
    public DrawerModel withUserID(Integer userID) {
        this.userID = userID;
        return this;
    }

    /**
     * Get the userFullName value.
     *
     * @return the userFullName value
     */
    public String userFullName() {
        return this.userFullName;
    }

    /**
     * Set the userFullName value.
     *
     * @param userFullName the userFullName value to set
     * @return the DrawerModel object itself.
     */
    public DrawerModel withUserFullName(String userFullName) {
        this.userFullName = userFullName;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the DrawerModel object itself.
     */
    public DrawerModel withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the edition value.
     *
     * @return the edition value
     */
    public Integer edition() {
        return this.edition;
    }

    /**
     * Set the edition value.
     *
     * @param edition the edition value to set
     * @return the DrawerModel object itself.
     */
    public DrawerModel withEdition(Integer edition) {
        this.edition = edition;
        return this;
    }

    /**
     * Get the state value.
     *
     * @return the state value
     */
    public Integer state() {
        return this.state;
    }

    /**
     * Set the state value.
     *
     * @param state the state value to set
     * @return the DrawerModel object itself.
     */
    public DrawerModel withState(Integer state) {
        this.state = state;
        return this;
    }

    /**
     * Get the entityFeature value.
     *
     * @return the entityFeature value
     */
    public Integer entityFeature() {
        return this.entityFeature;
    }

    /**
     * Set the entityFeature value.
     *
     * @param entityFeature the entityFeature value to set
     * @return the DrawerModel object itself.
     */
    public DrawerModel withEntityFeature(Integer entityFeature) {
        this.entityFeature = entityFeature;
        return this;
    }

    /**
     * Get the attachmentFeature value.
     *
     * @return the attachmentFeature value
     */
    public Integer attachmentFeature() {
        return this.attachmentFeature;
    }

    /**
     * Set the attachmentFeature value.
     *
     * @param attachmentFeature the attachmentFeature value to set
     * @return the DrawerModel object itself.
     */
    public DrawerModel withAttachmentFeature(Integer attachmentFeature) {
        this.attachmentFeature = attachmentFeature;
        return this;
    }

    /**
     * Get the noteFeature value.
     *
     * @return the noteFeature value
     */
    public Integer noteFeature() {
        return this.noteFeature;
    }

    /**
     * Set the noteFeature value.
     *
     * @param noteFeature the noteFeature value to set
     * @return the DrawerModel object itself.
     */
    public DrawerModel withNoteFeature(Integer noteFeature) {
        this.noteFeature = noteFeature;
        return this;
    }

    /**
     * Get the reservedInt1 value.
     *
     * @return the reservedInt1 value
     */
    public Integer reservedInt1() {
        return this.reservedInt1;
    }

    /**
     * Set the reservedInt1 value.
     *
     * @param reservedInt1 the reservedInt1 value to set
     * @return the DrawerModel object itself.
     */
    public DrawerModel withReservedInt1(Integer reservedInt1) {
        this.reservedInt1 = reservedInt1;
        return this;
    }

    /**
     * Get the reservedInt2 value.
     *
     * @return the reservedInt2 value
     */
    public Integer reservedInt2() {
        return this.reservedInt2;
    }

    /**
     * Set the reservedInt2 value.
     *
     * @param reservedInt2 the reservedInt2 value to set
     * @return the DrawerModel object itself.
     */
    public DrawerModel withReservedInt2(Integer reservedInt2) {
        this.reservedInt2 = reservedInt2;
        return this;
    }

    /**
     * Get the reservedString1 value.
     *
     * @return the reservedString1 value
     */
    public String reservedString1() {
        return this.reservedString1;
    }

    /**
     * Set the reservedString1 value.
     *
     * @param reservedString1 the reservedString1 value to set
     * @return the DrawerModel object itself.
     */
    public DrawerModel withReservedString1(String reservedString1) {
        this.reservedString1 = reservedString1;
        return this;
    }

    /**
     * Get the reservedString2 value.
     *
     * @return the reservedString2 value
     */
    public String reservedString2() {
        return this.reservedString2;
    }

    /**
     * Set the reservedString2 value.
     *
     * @param reservedString2 the reservedString2 value to set
     * @return the DrawerModel object itself.
     */
    public DrawerModel withReservedString2(String reservedString2) {
        this.reservedString2 = reservedString2;
        return this;
    }

}
