/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package softheon.enterprise.api.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Entity Content Model.
 */
public class EntityContentModel {
    /**
     * Gets or sets the content of the entity. Possible values include: 'None',
     * 'All', 'Profiles', 'Attachments', 'Notes', 'Links', 'Events'.
     */
    @JsonProperty(value = "EntityContent")
    private String entityContent;

    /**
     * Get the entityContent value.
     *
     * @return the entityContent value
     */
    public String entityContent() {
        return this.entityContent;
    }

    /**
     * Set the entityContent value.
     *
     * @param entityContent the entityContent value to set
     * @return the EntityContentModel object itself.
     */
    public EntityContentModel withEntityContent(String entityContent) {
        this.entityContent = entityContent;
        return this;
    }

}
