/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package softheon.enterprise.api.client.models;

import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Model for the GET Event input parameters.
 */
public class GetEventRequestModel {
    /**
     * Gets or sets the drawer identifier.
     */
    @JsonProperty(value = "DrawerID", required = true)
    private int drawerID;

    /**
     * Gets or sets the entity identifier.
     */
    @JsonProperty(value = "EntityID", required = true)
    private int entityID;

    /**
     * Gets or sets the type. Possible values include: 'Undefined', 'Fatal',
     * 'Warning', 'Info', 'Debug', 'Process', 'RPC', 'SQL', 'DDE'.
     */
    @JsonProperty(value = "Type")
    private String type;

    /**
     * Gets or sets the minimum event time.
     */
    @JsonProperty(value = "MinEventTime")
    private DateTime minEventTime;

    /**
     * Gets or sets the maximum event time.
     */
    @JsonProperty(value = "MaxEventTime")
    private DateTime maxEventTime;

    /**
     * Gets or sets the event user identifier.
     */
    @JsonProperty(value = "EventUserID")
    private Integer eventUserID;

    /**
     * Gets or sets the event group identifier.
     */
    @JsonProperty(value = "EventGroupID")
    private Integer eventGroupID;

    /**
     * Gets or sets the category. Possible values include: 'Undefined',
     * 'Entity', 'Profile', 'Attachment', 'Discussion', 'Field', 'Workflow'.
     */
    @JsonProperty(value = "Category")
    private String category;

    /**
     * Gets or sets the class. Possible values include: 'Undefined',
     * 'Application', 'Security', 'System'.
     */
    @JsonProperty(value = "Class")
    private String classProperty;

    /**
     * Gets or sets the operation. Possible values include: 'Undefined',
     * 'Insert', 'Update', 'Delete', 'Copy', 'Lock', 'Unlock', 'Open', 'Close',
     * 'Checkout', 'Checkin', 'View', 'Merge', 'Split', 'Classify', 'Null',
     * 'OpenWF', 'Remove', 'ReturnToTop', 'ReturnToBottom', 'Accept',
     * 'Suspend', 'Reject', 'Route', 'Forward', 'Reply', 'Reassign', 'Reset',
     * 'Override', 'Rollback', 'Archive'.
     */
    @JsonProperty(value = "Operation")
    private String operation;

    /**
     * Gets or sets the minimum processing time.
     */
    @JsonProperty(value = "MinProcessingTime")
    private Integer minProcessingTime;

    /**
     * Gets or sets the maximum processing time.
     */
    @JsonProperty(value = "MaxProcessingTime")
    private Integer maxProcessingTime;

    /**
     * Gets or sets the page number.
     */
    @JsonProperty(value = "Page")
    private Integer page;

    /**
     * Gets or sets the size of the page.
     */
    @JsonProperty(value = "PageSize")
    private Integer pageSize;

    /**
     * Gets or sets the order. Possible values include: 'Unspecified',
     * 'Ascending', 'Descending'.
     */
    @JsonProperty(value = "SortOrder")
    private String sortOrder;

    /**
     * Gets or sets the column to order by. Possible values include: 'ID',
     * 'Type', 'EventTime'.
     */
    @JsonProperty(value = "SortBy")
    private String sortBy;

    /**
     * Get the drawerID value.
     *
     * @return the drawerID value
     */
    public int drawerID() {
        return this.drawerID;
    }

    /**
     * Set the drawerID value.
     *
     * @param drawerID the drawerID value to set
     * @return the GetEventRequestModel object itself.
     */
    public GetEventRequestModel withDrawerID(int drawerID) {
        this.drawerID = drawerID;
        return this;
    }

    /**
     * Get the entityID value.
     *
     * @return the entityID value
     */
    public int entityID() {
        return this.entityID;
    }

    /**
     * Set the entityID value.
     *
     * @param entityID the entityID value to set
     * @return the GetEventRequestModel object itself.
     */
    public GetEventRequestModel withEntityID(int entityID) {
        this.entityID = entityID;
        return this;
    }

    /**
     * Get the type value.
     *
     * @return the type value
     */
    public String type() {
        return this.type;
    }

    /**
     * Set the type value.
     *
     * @param type the type value to set
     * @return the GetEventRequestModel object itself.
     */
    public GetEventRequestModel withType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get the minEventTime value.
     *
     * @return the minEventTime value
     */
    public DateTime minEventTime() {
        return this.minEventTime;
    }

    /**
     * Set the minEventTime value.
     *
     * @param minEventTime the minEventTime value to set
     * @return the GetEventRequestModel object itself.
     */
    public GetEventRequestModel withMinEventTime(DateTime minEventTime) {
        this.minEventTime = minEventTime;
        return this;
    }

    /**
     * Get the maxEventTime value.
     *
     * @return the maxEventTime value
     */
    public DateTime maxEventTime() {
        return this.maxEventTime;
    }

    /**
     * Set the maxEventTime value.
     *
     * @param maxEventTime the maxEventTime value to set
     * @return the GetEventRequestModel object itself.
     */
    public GetEventRequestModel withMaxEventTime(DateTime maxEventTime) {
        this.maxEventTime = maxEventTime;
        return this;
    }

    /**
     * Get the eventUserID value.
     *
     * @return the eventUserID value
     */
    public Integer eventUserID() {
        return this.eventUserID;
    }

    /**
     * Set the eventUserID value.
     *
     * @param eventUserID the eventUserID value to set
     * @return the GetEventRequestModel object itself.
     */
    public GetEventRequestModel withEventUserID(Integer eventUserID) {
        this.eventUserID = eventUserID;
        return this;
    }

    /**
     * Get the eventGroupID value.
     *
     * @return the eventGroupID value
     */
    public Integer eventGroupID() {
        return this.eventGroupID;
    }

    /**
     * Set the eventGroupID value.
     *
     * @param eventGroupID the eventGroupID value to set
     * @return the GetEventRequestModel object itself.
     */
    public GetEventRequestModel withEventGroupID(Integer eventGroupID) {
        this.eventGroupID = eventGroupID;
        return this;
    }

    /**
     * Get the category value.
     *
     * @return the category value
     */
    public String category() {
        return this.category;
    }

    /**
     * Set the category value.
     *
     * @param category the category value to set
     * @return the GetEventRequestModel object itself.
     */
    public GetEventRequestModel withCategory(String category) {
        this.category = category;
        return this;
    }

    /**
     * Get the classProperty value.
     *
     * @return the classProperty value
     */
    public String classProperty() {
        return this.classProperty;
    }

    /**
     * Set the classProperty value.
     *
     * @param classProperty the classProperty value to set
     * @return the GetEventRequestModel object itself.
     */
    public GetEventRequestModel withClassProperty(String classProperty) {
        this.classProperty = classProperty;
        return this;
    }

    /**
     * Get the operation value.
     *
     * @return the operation value
     */
    public String operation() {
        return this.operation;
    }

    /**
     * Set the operation value.
     *
     * @param operation the operation value to set
     * @return the GetEventRequestModel object itself.
     */
    public GetEventRequestModel withOperation(String operation) {
        this.operation = operation;
        return this;
    }

    /**
     * Get the minProcessingTime value.
     *
     * @return the minProcessingTime value
     */
    public Integer minProcessingTime() {
        return this.minProcessingTime;
    }

    /**
     * Set the minProcessingTime value.
     *
     * @param minProcessingTime the minProcessingTime value to set
     * @return the GetEventRequestModel object itself.
     */
    public GetEventRequestModel withMinProcessingTime(Integer minProcessingTime) {
        this.minProcessingTime = minProcessingTime;
        return this;
    }

    /**
     * Get the maxProcessingTime value.
     *
     * @return the maxProcessingTime value
     */
    public Integer maxProcessingTime() {
        return this.maxProcessingTime;
    }

    /**
     * Set the maxProcessingTime value.
     *
     * @param maxProcessingTime the maxProcessingTime value to set
     * @return the GetEventRequestModel object itself.
     */
    public GetEventRequestModel withMaxProcessingTime(Integer maxProcessingTime) {
        this.maxProcessingTime = maxProcessingTime;
        return this;
    }

    /**
     * Get the page value.
     *
     * @return the page value
     */
    public Integer page() {
        return this.page;
    }

    /**
     * Set the page value.
     *
     * @param page the page value to set
     * @return the GetEventRequestModel object itself.
     */
    public GetEventRequestModel withPage(Integer page) {
        this.page = page;
        return this;
    }

    /**
     * Get the pageSize value.
     *
     * @return the pageSize value
     */
    public Integer pageSize() {
        return this.pageSize;
    }

    /**
     * Set the pageSize value.
     *
     * @param pageSize the pageSize value to set
     * @return the GetEventRequestModel object itself.
     */
    public GetEventRequestModel withPageSize(Integer pageSize) {
        this.pageSize = pageSize;
        return this;
    }

    /**
     * Get the sortOrder value.
     *
     * @return the sortOrder value
     */
    public String sortOrder() {
        return this.sortOrder;
    }

    /**
     * Set the sortOrder value.
     *
     * @param sortOrder the sortOrder value to set
     * @return the GetEventRequestModel object itself.
     */
    public GetEventRequestModel withSortOrder(String sortOrder) {
        this.sortOrder = sortOrder;
        return this;
    }

    /**
     * Get the sortBy value.
     *
     * @return the sortBy value
     */
    public String sortBy() {
        return this.sortBy;
    }

    /**
     * Set the sortBy value.
     *
     * @param sortBy the sortBy value to set
     * @return the GetEventRequestModel object itself.
     */
    public GetEventRequestModel withSortBy(String sortBy) {
        this.sortBy = sortBy;
        return this;
    }

}
