/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package softheon.enterprise.api.client.models;

import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Model for the GET Note input parameters.
 */
public class GetNoteRequestModel {
    /**
     * Gets or sets the drawer identifier.
     */
    @JsonProperty(value = "DrawerID", required = true)
    private int drawerID;

    /**
     * Gets or sets the entity identifier.
     */
    @JsonProperty(value = "EntityID")
    private Integer entityID;

    /**
     * Gets or sets the name.
     */
    @JsonProperty(value = "Name")
    private String name;

    /**
     * Gets or sets the creator user identifier.
     */
    @JsonProperty(value = "CreatorUserID")
    private Integer creatorUserID;

    /**
     * Gets or sets the modifier user identifier.
     */
    @JsonProperty(value = "ModifierUserID")
    private Integer modifierUserID;

    /**
     * Gets or sets the minimum creation time.
     */
    @JsonProperty(value = "MinCreationTime")
    private DateTime minCreationTime;

    /**
     * Gets or sets the maximum creation time.
     */
    @JsonProperty(value = "MaxCreationTime")
    private DateTime maxCreationTime;

    /**
     * Gets or sets the minimum modification time.
     */
    @JsonProperty(value = "MinModificationTime")
    private DateTime minModificationTime;

    /**
     * Gets or sets the maximum modification time.
     */
    @JsonProperty(value = "MaxModificationTime")
    private DateTime maxModificationTime;

    /**
     * Gets or sets the parent note identifier.
     */
    @JsonProperty(value = "ParentID")
    private Integer parentID;

    /**
     * Gets or sets the page number.
     */
    @JsonProperty(value = "Page")
    private Integer page;

    /**
     * Gets or sets the size of the page.
     */
    @JsonProperty(value = "PageSize")
    private Integer pageSize;

    /**
     * Gets or sets the order. Possible values include: 'Unspecified',
     * 'Ascending', 'Descending'.
     */
    @JsonProperty(value = "SortOrder")
    private String sortOrder;

    /**
     * Gets or sets the column to order by. Possible values include: 'ID',
     * 'EntityID', 'Name', 'CreationTime', 'ModificationTime'.
     */
    @JsonProperty(value = "SortBy")
    private String sortBy;

    /**
     * Get the drawerID value.
     *
     * @return the drawerID value
     */
    public int drawerID() {
        return this.drawerID;
    }

    /**
     * Set the drawerID value.
     *
     * @param drawerID the drawerID value to set
     * @return the GetNoteRequestModel object itself.
     */
    public GetNoteRequestModel withDrawerID(int drawerID) {
        this.drawerID = drawerID;
        return this;
    }

    /**
     * Get the entityID value.
     *
     * @return the entityID value
     */
    public Integer entityID() {
        return this.entityID;
    }

    /**
     * Set the entityID value.
     *
     * @param entityID the entityID value to set
     * @return the GetNoteRequestModel object itself.
     */
    public GetNoteRequestModel withEntityID(Integer entityID) {
        this.entityID = entityID;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the GetNoteRequestModel object itself.
     */
    public GetNoteRequestModel withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the creatorUserID value.
     *
     * @return the creatorUserID value
     */
    public Integer creatorUserID() {
        return this.creatorUserID;
    }

    /**
     * Set the creatorUserID value.
     *
     * @param creatorUserID the creatorUserID value to set
     * @return the GetNoteRequestModel object itself.
     */
    public GetNoteRequestModel withCreatorUserID(Integer creatorUserID) {
        this.creatorUserID = creatorUserID;
        return this;
    }

    /**
     * Get the modifierUserID value.
     *
     * @return the modifierUserID value
     */
    public Integer modifierUserID() {
        return this.modifierUserID;
    }

    /**
     * Set the modifierUserID value.
     *
     * @param modifierUserID the modifierUserID value to set
     * @return the GetNoteRequestModel object itself.
     */
    public GetNoteRequestModel withModifierUserID(Integer modifierUserID) {
        this.modifierUserID = modifierUserID;
        return this;
    }

    /**
     * Get the minCreationTime value.
     *
     * @return the minCreationTime value
     */
    public DateTime minCreationTime() {
        return this.minCreationTime;
    }

    /**
     * Set the minCreationTime value.
     *
     * @param minCreationTime the minCreationTime value to set
     * @return the GetNoteRequestModel object itself.
     */
    public GetNoteRequestModel withMinCreationTime(DateTime minCreationTime) {
        this.minCreationTime = minCreationTime;
        return this;
    }

    /**
     * Get the maxCreationTime value.
     *
     * @return the maxCreationTime value
     */
    public DateTime maxCreationTime() {
        return this.maxCreationTime;
    }

    /**
     * Set the maxCreationTime value.
     *
     * @param maxCreationTime the maxCreationTime value to set
     * @return the GetNoteRequestModel object itself.
     */
    public GetNoteRequestModel withMaxCreationTime(DateTime maxCreationTime) {
        this.maxCreationTime = maxCreationTime;
        return this;
    }

    /**
     * Get the minModificationTime value.
     *
     * @return the minModificationTime value
     */
    public DateTime minModificationTime() {
        return this.minModificationTime;
    }

    /**
     * Set the minModificationTime value.
     *
     * @param minModificationTime the minModificationTime value to set
     * @return the GetNoteRequestModel object itself.
     */
    public GetNoteRequestModel withMinModificationTime(DateTime minModificationTime) {
        this.minModificationTime = minModificationTime;
        return this;
    }

    /**
     * Get the maxModificationTime value.
     *
     * @return the maxModificationTime value
     */
    public DateTime maxModificationTime() {
        return this.maxModificationTime;
    }

    /**
     * Set the maxModificationTime value.
     *
     * @param maxModificationTime the maxModificationTime value to set
     * @return the GetNoteRequestModel object itself.
     */
    public GetNoteRequestModel withMaxModificationTime(DateTime maxModificationTime) {
        this.maxModificationTime = maxModificationTime;
        return this;
    }

    /**
     * Get the parentID value.
     *
     * @return the parentID value
     */
    public Integer parentID() {
        return this.parentID;
    }

    /**
     * Set the parentID value.
     *
     * @param parentID the parentID value to set
     * @return the GetNoteRequestModel object itself.
     */
    public GetNoteRequestModel withParentID(Integer parentID) {
        this.parentID = parentID;
        return this;
    }

    /**
     * Get the page value.
     *
     * @return the page value
     */
    public Integer page() {
        return this.page;
    }

    /**
     * Set the page value.
     *
     * @param page the page value to set
     * @return the GetNoteRequestModel object itself.
     */
    public GetNoteRequestModel withPage(Integer page) {
        this.page = page;
        return this;
    }

    /**
     * Get the pageSize value.
     *
     * @return the pageSize value
     */
    public Integer pageSize() {
        return this.pageSize;
    }

    /**
     * Set the pageSize value.
     *
     * @param pageSize the pageSize value to set
     * @return the GetNoteRequestModel object itself.
     */
    public GetNoteRequestModel withPageSize(Integer pageSize) {
        this.pageSize = pageSize;
        return this;
    }

    /**
     * Get the sortOrder value.
     *
     * @return the sortOrder value
     */
    public String sortOrder() {
        return this.sortOrder;
    }

    /**
     * Set the sortOrder value.
     *
     * @param sortOrder the sortOrder value to set
     * @return the GetNoteRequestModel object itself.
     */
    public GetNoteRequestModel withSortOrder(String sortOrder) {
        this.sortOrder = sortOrder;
        return this;
    }

    /**
     * Get the sortBy value.
     *
     * @return the sortBy value
     */
    public String sortBy() {
        return this.sortBy;
    }

    /**
     * Set the sortBy value.
     *
     * @param sortBy the sortBy value to set
     * @return the GetNoteRequestModel object itself.
     */
    public GetNoteRequestModel withSortBy(String sortBy) {
        this.sortBy = sortBy;
        return this;
    }

}
