/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package softheon.enterprise.api.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The model that is sent in response to a GET request for Groups.
 */
public class GroupModel {
    /**
     * Gets or sets the group identifier.
     */
    @JsonProperty(value = "ID")
    private Integer id;

    /**
     * Gets or sets the queue count.
     */
    @JsonProperty(value = "QueueCount")
    private Integer queueCount;

    /**
     * Gets or sets the user count.
     */
    @JsonProperty(value = "UserCount")
    private Integer userCount;

    /**
     * Gets or sets the user identifier.
     */
    @JsonProperty(value = "UserID")
    private Integer userID;

    /**
     * Gets or sets the name.
     */
    @JsonProperty(value = "Name", required = true)
    private String name;

    /**
     * Gets or sets the type. Possible values include: 'Generic', 'Access',
     * 'Role'.
     */
    @JsonProperty(value = "Type")
    private String type;

    /**
     * Gets or sets the state. Possible values include: 'Inactive', 'Active'.
     */
    @JsonProperty(value = "State")
    private String state;

    /**
     * Gets or sets the reserved int1.
     */
    @JsonProperty(value = "ReservedInt1")
    private Integer reservedInt1;

    /**
     * Gets or sets the reserved int2.
     */
    @JsonProperty(value = "ReservedInt2")
    private Integer reservedInt2;

    /**
     * Gets or sets the reserved string1.
     */
    @JsonProperty(value = "ReservedString1")
    private String reservedString1;

    /**
     * Gets or sets the reserved string2.
     */
    @JsonProperty(value = "ReservedString2")
    private String reservedString2;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public Integer id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the GroupModel object itself.
     */
    public GroupModel withId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Get the queueCount value.
     *
     * @return the queueCount value
     */
    public Integer queueCount() {
        return this.queueCount;
    }

    /**
     * Set the queueCount value.
     *
     * @param queueCount the queueCount value to set
     * @return the GroupModel object itself.
     */
    public GroupModel withQueueCount(Integer queueCount) {
        this.queueCount = queueCount;
        return this;
    }

    /**
     * Get the userCount value.
     *
     * @return the userCount value
     */
    public Integer userCount() {
        return this.userCount;
    }

    /**
     * Set the userCount value.
     *
     * @param userCount the userCount value to set
     * @return the GroupModel object itself.
     */
    public GroupModel withUserCount(Integer userCount) {
        this.userCount = userCount;
        return this;
    }

    /**
     * Get the userID value.
     *
     * @return the userID value
     */
    public Integer userID() {
        return this.userID;
    }

    /**
     * Set the userID value.
     *
     * @param userID the userID value to set
     * @return the GroupModel object itself.
     */
    public GroupModel withUserID(Integer userID) {
        this.userID = userID;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the GroupModel object itself.
     */
    public GroupModel withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the type value.
     *
     * @return the type value
     */
    public String type() {
        return this.type;
    }

    /**
     * Set the type value.
     *
     * @param type the type value to set
     * @return the GroupModel object itself.
     */
    public GroupModel withType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get the state value.
     *
     * @return the state value
     */
    public String state() {
        return this.state;
    }

    /**
     * Set the state value.
     *
     * @param state the state value to set
     * @return the GroupModel object itself.
     */
    public GroupModel withState(String state) {
        this.state = state;
        return this;
    }

    /**
     * Get the reservedInt1 value.
     *
     * @return the reservedInt1 value
     */
    public Integer reservedInt1() {
        return this.reservedInt1;
    }

    /**
     * Set the reservedInt1 value.
     *
     * @param reservedInt1 the reservedInt1 value to set
     * @return the GroupModel object itself.
     */
    public GroupModel withReservedInt1(Integer reservedInt1) {
        this.reservedInt1 = reservedInt1;
        return this;
    }

    /**
     * Get the reservedInt2 value.
     *
     * @return the reservedInt2 value
     */
    public Integer reservedInt2() {
        return this.reservedInt2;
    }

    /**
     * Set the reservedInt2 value.
     *
     * @param reservedInt2 the reservedInt2 value to set
     * @return the GroupModel object itself.
     */
    public GroupModel withReservedInt2(Integer reservedInt2) {
        this.reservedInt2 = reservedInt2;
        return this;
    }

    /**
     * Get the reservedString1 value.
     *
     * @return the reservedString1 value
     */
    public String reservedString1() {
        return this.reservedString1;
    }

    /**
     * Set the reservedString1 value.
     *
     * @param reservedString1 the reservedString1 value to set
     * @return the GroupModel object itself.
     */
    public GroupModel withReservedString1(String reservedString1) {
        this.reservedString1 = reservedString1;
        return this;
    }

    /**
     * Get the reservedString2 value.
     *
     * @return the reservedString2 value
     */
    public String reservedString2() {
        return this.reservedString2;
    }

    /**
     * Set the reservedString2 value.
     *
     * @param reservedString2 the reservedString2 value to set
     * @return the GroupModel object itself.
     */
    public GroupModel withReservedString2(String reservedString2) {
        this.reservedString2 = reservedString2;
        return this;
    }

}
