/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package softheon.enterprise.api.client.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Insert Entity Model.
 */
public class InsertEntityRequestModel {
    /**
     * Gets or sets the profiles.
     */
    @JsonProperty(value = "Profiles")
    private List<ProfileModel> profiles;

    /**
     * Gets or sets the access control list.
     */
    @JsonProperty(value = "Acl")
    private Integer acl;

    /**
     * Gets or sets the type.
     */
    @JsonProperty(value = "Type")
    private Integer type;

    /**
     * Gets or sets the Name.
     */
    @JsonProperty(value = "Name", required = true)
    private String name;

    /**
     * Get the profiles value.
     *
     * @return the profiles value
     */
    public List<ProfileModel> profiles() {
        return this.profiles;
    }

    /**
     * Set the profiles value.
     *
     * @param profiles the profiles value to set
     * @return the InsertEntityRequestModel object itself.
     */
    public InsertEntityRequestModel withProfiles(List<ProfileModel> profiles) {
        this.profiles = profiles;
        return this;
    }

    /**
     * Get the acl value.
     *
     * @return the acl value
     */
    public Integer acl() {
        return this.acl;
    }

    /**
     * Set the acl value.
     *
     * @param acl the acl value to set
     * @return the InsertEntityRequestModel object itself.
     */
    public InsertEntityRequestModel withAcl(Integer acl) {
        this.acl = acl;
        return this;
    }

    /**
     * Get the type value.
     *
     * @return the type value
     */
    public Integer type() {
        return this.type;
    }

    /**
     * Set the type value.
     *
     * @param type the type value to set
     * @return the InsertEntityRequestModel object itself.
     */
    public InsertEntityRequestModel withType(Integer type) {
        this.type = type;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the InsertEntityRequestModel object itself.
     */
    public InsertEntityRequestModel withName(String name) {
        this.name = name;
        return this;
    }

}
