/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package softheon.enterprise.api.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Model for POST Group input Parameters.
 */
public class InsertGroupRequestModel {
    /**
     * Gets or sets the name.
     */
    @JsonProperty(value = "Name", required = true)
    private String name;

    /**
     * Gets or sets the type. Possible values include: 'Generic', 'Access',
     * 'Role'.
     */
    @JsonProperty(value = "Type")
    private String type;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the InsertGroupRequestModel object itself.
     */
    public InsertGroupRequestModel withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the type value.
     *
     * @return the type value
     */
    public String type() {
        return this.type;
    }

    /**
     * Set the type value.
     *
     * @param type the type value to set
     * @return the InsertGroupRequestModel object itself.
     */
    public InsertGroupRequestModel withType(String type) {
        this.type = type;
        return this;
    }

}
