/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package softheon.enterprise.api.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The LookupField model.
 */
public class LookupField {
    /**
     * The column property.
     */
    @JsonProperty(value = "Column")
    private String column;

    /**
     * The profileIndex property.
     */
    @JsonProperty(value = "ProfileIndex")
    private Integer profileIndex;

    /**
     * The fieldIndex property.
     */
    @JsonProperty(value = "FieldIndex")
    private Integer fieldIndex;

    /**
     * The extensionIndex property.
     */
    @JsonProperty(value = "ExtensionIndex")
    private Integer extensionIndex;

    /**
     * Get the column value.
     *
     * @return the column value
     */
    public String column() {
        return this.column;
    }

    /**
     * Set the column value.
     *
     * @param column the column value to set
     * @return the LookupField object itself.
     */
    public LookupField withColumn(String column) {
        this.column = column;
        return this;
    }

    /**
     * Get the profileIndex value.
     *
     * @return the profileIndex value
     */
    public Integer profileIndex() {
        return this.profileIndex;
    }

    /**
     * Set the profileIndex value.
     *
     * @param profileIndex the profileIndex value to set
     * @return the LookupField object itself.
     */
    public LookupField withProfileIndex(Integer profileIndex) {
        this.profileIndex = profileIndex;
        return this;
    }

    /**
     * Get the fieldIndex value.
     *
     * @return the fieldIndex value
     */
    public Integer fieldIndex() {
        return this.fieldIndex;
    }

    /**
     * Set the fieldIndex value.
     *
     * @param fieldIndex the fieldIndex value to set
     * @return the LookupField object itself.
     */
    public LookupField withFieldIndex(Integer fieldIndex) {
        this.fieldIndex = fieldIndex;
        return this;
    }

    /**
     * Get the extensionIndex value.
     *
     * @return the extensionIndex value
     */
    public Integer extensionIndex() {
        return this.extensionIndex;
    }

    /**
     * Set the extensionIndex value.
     *
     * @param extensionIndex the extensionIndex value to set
     * @return the LookupField object itself.
     */
    public LookupField withExtensionIndex(Integer extensionIndex) {
        this.extensionIndex = extensionIndex;
        return this;
    }

}
