/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package softheon.enterprise.api.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Note Base Class.
 */
public class NoteBase {
    /**
     * Gets or sets the acl.
     */
    @JsonProperty(value = "Acl")
    private Integer acl;

    /**
     * Gets or sets the name.
     */
    @JsonProperty(value = "Name")
    private String name;

    /**
     * Gets or sets the note.
     */
    @JsonProperty(value = "Note")
    private String note;

    /**
     * Get the acl value.
     *
     * @return the acl value
     */
    public Integer acl() {
        return this.acl;
    }

    /**
     * Set the acl value.
     *
     * @param acl the acl value to set
     * @return the NoteBase object itself.
     */
    public NoteBase withAcl(Integer acl) {
        this.acl = acl;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the NoteBase object itself.
     */
    public NoteBase withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the note value.
     *
     * @return the note value
     */
    public String note() {
        return this.note;
    }

    /**
     * Set the note value.
     *
     * @param note the note value to set
     * @return the NoteBase object itself.
     */
    public NoteBase withNote(String note) {
        this.note = note;
        return this;
    }

}
