/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package softheon.enterprise.api.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Defines properties and methods for Queue Assignment.
 */
public class QueueAssignmentModel {
    /**
     * Gets or sets the unique queue identifier.
     */
    @JsonProperty(value = "QueueID")
    private Integer queueID;

    /**
     * Gets or sets the user identifier.
     */
    @JsonProperty(value = "UserID")
    private Integer userID;

    /**
     * Gets or sets the group identifier.
     */
    @JsonProperty(value = "GroupID")
    private Integer groupID;

    /**
     * Gets or sets the queue assignment type. Possible values include:
     * 'Unspecified', 'Primary', 'Secondary'.
     */
    @JsonProperty(value = "Type")
    private String type;

    /**
     * Gets or sets the sort order.
     */
    @JsonProperty(value = "Order")
    private Integer order;

    /**
     * Gets or sets the task sort column. Possible values include: 'TaskID',
     * 'QueueID', 'DrawerID', 'AddressID', 'ObjectID', 'ObjectType', 'State',
     * 'Priority', 'Description', 'Message1', 'Message2', 'Message3',
     * 'Message4', 'Message5', 'OwnerUserID', 'OwnerGroupID',
     * 'EffectiveUserID', 'EffectiveGroupID', 'PreviousQueueID', 'NextQueueID',
     * 'InsertionTime', 'ResolutionTime', 'TaskFileAttachment', 'ReservedInt1',
     * 'ReservedString1'.
     */
    @JsonProperty(value = "TaskSortColumn")
    private String taskSortColumn;

    /**
     * Gets or sets the state. Possible values include: 'Unspecified',
     * 'Inactive', 'Active'.
     */
    @JsonProperty(value = "State")
    private String state;

    /**
     * Gets or sets the type of the fetch. Possible values include:
     * 'Unspecified', 'Manual', 'Push'.
     */
    @JsonProperty(value = "FetchType")
    private String fetchType;

    /**
     * Get the queueID value.
     *
     * @return the queueID value
     */
    public Integer queueID() {
        return this.queueID;
    }

    /**
     * Set the queueID value.
     *
     * @param queueID the queueID value to set
     * @return the QueueAssignmentModel object itself.
     */
    public QueueAssignmentModel withQueueID(Integer queueID) {
        this.queueID = queueID;
        return this;
    }

    /**
     * Get the userID value.
     *
     * @return the userID value
     */
    public Integer userID() {
        return this.userID;
    }

    /**
     * Set the userID value.
     *
     * @param userID the userID value to set
     * @return the QueueAssignmentModel object itself.
     */
    public QueueAssignmentModel withUserID(Integer userID) {
        this.userID = userID;
        return this;
    }

    /**
     * Get the groupID value.
     *
     * @return the groupID value
     */
    public Integer groupID() {
        return this.groupID;
    }

    /**
     * Set the groupID value.
     *
     * @param groupID the groupID value to set
     * @return the QueueAssignmentModel object itself.
     */
    public QueueAssignmentModel withGroupID(Integer groupID) {
        this.groupID = groupID;
        return this;
    }

    /**
     * Get the type value.
     *
     * @return the type value
     */
    public String type() {
        return this.type;
    }

    /**
     * Set the type value.
     *
     * @param type the type value to set
     * @return the QueueAssignmentModel object itself.
     */
    public QueueAssignmentModel withType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get the order value.
     *
     * @return the order value
     */
    public Integer order() {
        return this.order;
    }

    /**
     * Set the order value.
     *
     * @param order the order value to set
     * @return the QueueAssignmentModel object itself.
     */
    public QueueAssignmentModel withOrder(Integer order) {
        this.order = order;
        return this;
    }

    /**
     * Get the taskSortColumn value.
     *
     * @return the taskSortColumn value
     */
    public String taskSortColumn() {
        return this.taskSortColumn;
    }

    /**
     * Set the taskSortColumn value.
     *
     * @param taskSortColumn the taskSortColumn value to set
     * @return the QueueAssignmentModel object itself.
     */
    public QueueAssignmentModel withTaskSortColumn(String taskSortColumn) {
        this.taskSortColumn = taskSortColumn;
        return this;
    }

    /**
     * Get the state value.
     *
     * @return the state value
     */
    public String state() {
        return this.state;
    }

    /**
     * Set the state value.
     *
     * @param state the state value to set
     * @return the QueueAssignmentModel object itself.
     */
    public QueueAssignmentModel withState(String state) {
        this.state = state;
        return this;
    }

    /**
     * Get the fetchType value.
     *
     * @return the fetchType value
     */
    public String fetchType() {
        return this.fetchType;
    }

    /**
     * Set the fetchType value.
     *
     * @param fetchType the fetchType value to set
     * @return the QueueAssignmentModel object itself.
     */
    public QueueAssignmentModel withFetchType(String fetchType) {
        this.fetchType = fetchType;
        return this;
    }

}
