/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package softheon.enterprise.api.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Model for PUT Queue parameters.
 */
public class QueueBase {
    /**
     * Gets or sets the name.
     */
    @JsonProperty(value = "Name")
    private String name;

    /**
     * Gets or sets the alias.
     */
    @JsonProperty(value = "Alias")
    private String alias;

    /**
     * Gets or sets the state. Possible values include: 'Inactive', 'Active'.
     */
    @JsonProperty(value = "State")
    private String state;

    /**
     * Gets or sets the type. Possible values include: 'Inbound', 'Outbound',
     * 'Access', 'Any', 'Shared', 'Public', 'Recycle', 'Fax', 'Print', 'Scan',
     * 'Ocr', 'Workflow', 'Schedule', 'System', 'Other', 'CdoInfostore',
     * 'CdoFolder'.
     */
    @JsonProperty(value = "Type")
    private String type;

    /**
     * Gets or sets the category.
     */
    @JsonProperty(value = "Category")
    private String category;

    /**
     * Gets or sets the description.
     */
    @JsonProperty(value = "Description")
    private String description;

    /**
     * Gets or sets the reserved integer 1.
     */
    @JsonProperty(value = "ReservedInt1")
    private Integer reservedInt1;

    /**
     * Gets or sets the reserved integer 2.
     */
    @JsonProperty(value = "ReservedInt2")
    private Integer reservedInt2;

    /**
     * Gets or sets the reserved string 1.
     */
    @JsonProperty(value = "ReservedString1")
    private String reservedString1;

    /**
     * Gets or sets the reserved string 2.
     */
    @JsonProperty(value = "ReservedString2")
    private String reservedString2;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the QueueBase object itself.
     */
    public QueueBase withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the alias value.
     *
     * @return the alias value
     */
    public String alias() {
        return this.alias;
    }

    /**
     * Set the alias value.
     *
     * @param alias the alias value to set
     * @return the QueueBase object itself.
     */
    public QueueBase withAlias(String alias) {
        this.alias = alias;
        return this;
    }

    /**
     * Get the state value.
     *
     * @return the state value
     */
    public String state() {
        return this.state;
    }

    /**
     * Set the state value.
     *
     * @param state the state value to set
     * @return the QueueBase object itself.
     */
    public QueueBase withState(String state) {
        this.state = state;
        return this;
    }

    /**
     * Get the type value.
     *
     * @return the type value
     */
    public String type() {
        return this.type;
    }

    /**
     * Set the type value.
     *
     * @param type the type value to set
     * @return the QueueBase object itself.
     */
    public QueueBase withType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get the category value.
     *
     * @return the category value
     */
    public String category() {
        return this.category;
    }

    /**
     * Set the category value.
     *
     * @param category the category value to set
     * @return the QueueBase object itself.
     */
    public QueueBase withCategory(String category) {
        this.category = category;
        return this;
    }

    /**
     * Get the description value.
     *
     * @return the description value
     */
    public String description() {
        return this.description;
    }

    /**
     * Set the description value.
     *
     * @param description the description value to set
     * @return the QueueBase object itself.
     */
    public QueueBase withDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get the reservedInt1 value.
     *
     * @return the reservedInt1 value
     */
    public Integer reservedInt1() {
        return this.reservedInt1;
    }

    /**
     * Set the reservedInt1 value.
     *
     * @param reservedInt1 the reservedInt1 value to set
     * @return the QueueBase object itself.
     */
    public QueueBase withReservedInt1(Integer reservedInt1) {
        this.reservedInt1 = reservedInt1;
        return this;
    }

    /**
     * Get the reservedInt2 value.
     *
     * @return the reservedInt2 value
     */
    public Integer reservedInt2() {
        return this.reservedInt2;
    }

    /**
     * Set the reservedInt2 value.
     *
     * @param reservedInt2 the reservedInt2 value to set
     * @return the QueueBase object itself.
     */
    public QueueBase withReservedInt2(Integer reservedInt2) {
        this.reservedInt2 = reservedInt2;
        return this;
    }

    /**
     * Get the reservedString1 value.
     *
     * @return the reservedString1 value
     */
    public String reservedString1() {
        return this.reservedString1;
    }

    /**
     * Set the reservedString1 value.
     *
     * @param reservedString1 the reservedString1 value to set
     * @return the QueueBase object itself.
     */
    public QueueBase withReservedString1(String reservedString1) {
        this.reservedString1 = reservedString1;
        return this;
    }

    /**
     * Get the reservedString2 value.
     *
     * @return the reservedString2 value
     */
    public String reservedString2() {
        return this.reservedString2;
    }

    /**
     * Set the reservedString2 value.
     *
     * @param reservedString2 the reservedString2 value to set
     * @return the QueueBase object itself.
     */
    public QueueBase withReservedString2(String reservedString2) {
        this.reservedString2 = reservedString2;
        return this;
    }

}
