/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package softheon.enterprise.api.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The model that is sent in response to a GET request for Workflow.
 */
public class WorkflowModel {
    /**
     * Gets or sets the identifier.
     */
    @JsonProperty(value = "ID")
    private Integer id;

    /**
     * Gets or sets the name.
     */
    @JsonProperty(value = "Name")
    private String name;

    /**
     * Gets or sets the type of the entity.
     */
    @JsonProperty(value = "EntityType")
    private Integer entityType;

    /**
     * Gets or sets the alias.
     */
    @JsonProperty(value = "Alias")
    private String alias;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public Integer id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the WorkflowModel object itself.
     */
    public WorkflowModel withId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the WorkflowModel object itself.
     */
    public WorkflowModel withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the entityType value.
     *
     * @return the entityType value
     */
    public Integer entityType() {
        return this.entityType;
    }

    /**
     * Set the entityType value.
     *
     * @param entityType the entityType value to set
     * @return the WorkflowModel object itself.
     */
    public WorkflowModel withEntityType(Integer entityType) {
        this.entityType = entityType;
        return this;
    }

    /**
     * Get the alias value.
     *
     * @return the alias value
     */
    public String alias() {
        return this.alias;
    }

    /**
     * Set the alias value.
     *
     * @param alias the alias value to set
     * @return the WorkflowModel object itself.
     */
    public WorkflowModel withAlias(String alias) {
        this.alias = alias;
        return this;
    }

}
