// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Softheon.Enterprise.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Attachment Version Model
    /// </summary>
    public partial class AttachmentVersionModel
    {
        /// <summary>
        /// Initializes a new instance of the AttachmentVersionModel class.
        /// </summary>
        public AttachmentVersionModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AttachmentVersionModel class.
        /// </summary>
        /// <param name="version">Gets or sets the indexed version
        /// value.</param>
        /// <param name="attachmentID">Gets or sets the attachment
        /// identifier.</param>
        /// <param name="name">Gets or sets the string.</param>
        /// <param name="creatorUserID">Gets or sets the creator
        /// identifier.</param>
        /// <param name="accessorUserID">Gets or sets the identifier of the
        /// user who accessed the attachment version.</param>
        /// <param name="accessTime">Gets or sets the time the version was last
        /// accessed.</param>
        /// <param name="creationTime">Gets or sets the creation time of the
        /// attachment version.</param>
        /// <param name="modificationTime">Gets or sets the modification time
        /// of the attachment version.</param>
        /// <param name="comment">Gets or sets the description comment of
        /// changes that were made.</param>
        /// <param name="reservedInt1">Gets or sets the reserved int1.</param>
        /// <param name="reservedInt2">Gets or sets the reserved int2.</param>
        /// <param name="reservedInt3">Gets or sets the reserved int3.</param>
        /// <param name="reservedInt4">Gets or sets the reserved int4.</param>
        /// <param name="reservedString1">Gets or sets the reserved
        /// string1.</param>
        /// <param name="reservedString2">Gets or sets the reserved
        /// string2.</param>
        public AttachmentVersionModel(int? version = default(int?), int? attachmentID = default(int?), string name = default(string), int? creatorUserID = default(int?), int? accessorUserID = default(int?), System.DateTime? accessTime = default(System.DateTime?), System.DateTime? creationTime = default(System.DateTime?), System.DateTime? modificationTime = default(System.DateTime?), string comment = default(string), int? reservedInt1 = default(int?), int? reservedInt2 = default(int?), int? reservedInt3 = default(int?), int? reservedInt4 = default(int?), string reservedString1 = default(string), string reservedString2 = default(string))
        {
            Version = version;
            AttachmentID = attachmentID;
            Name = name;
            CreatorUserID = creatorUserID;
            AccessorUserID = accessorUserID;
            AccessTime = accessTime;
            CreationTime = creationTime;
            ModificationTime = modificationTime;
            Comment = comment;
            ReservedInt1 = reservedInt1;
            ReservedInt2 = reservedInt2;
            ReservedInt3 = reservedInt3;
            ReservedInt4 = reservedInt4;
            ReservedString1 = reservedString1;
            ReservedString2 = reservedString2;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the indexed version value.
        /// </summary>
        [JsonProperty(PropertyName = "Version")]
        public int? Version { get; set; }

        /// <summary>
        /// Gets or sets the attachment identifier.
        /// </summary>
        [JsonProperty(PropertyName = "AttachmentID")]
        public int? AttachmentID { get; set; }

        /// <summary>
        /// Gets or sets the string.
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the creator identifier.
        /// </summary>
        [JsonProperty(PropertyName = "CreatorUserID")]
        public int? CreatorUserID { get; set; }

        /// <summary>
        /// Gets or sets the identifier of the user who accessed the attachment
        /// version.
        /// </summary>
        [JsonProperty(PropertyName = "AccessorUserID")]
        public int? AccessorUserID { get; set; }

        /// <summary>
        /// Gets or sets the time the version was last accessed.
        /// </summary>
        [JsonProperty(PropertyName = "AccessTime")]
        public System.DateTime? AccessTime { get; set; }

        /// <summary>
        /// Gets or sets the creation time of the attachment version.
        /// </summary>
        [JsonProperty(PropertyName = "CreationTime")]
        public System.DateTime? CreationTime { get; set; }

        /// <summary>
        /// Gets or sets the modification time of the attachment version.
        /// </summary>
        [JsonProperty(PropertyName = "ModificationTime")]
        public System.DateTime? ModificationTime { get; set; }

        /// <summary>
        /// Gets or sets the description comment of changes that were made.
        /// </summary>
        [JsonProperty(PropertyName = "Comment")]
        public string Comment { get; set; }

        /// <summary>
        /// Gets or sets the reserved int1.
        /// </summary>
        [JsonProperty(PropertyName = "ReservedInt1")]
        public int? ReservedInt1 { get; set; }

        /// <summary>
        /// Gets or sets the reserved int2.
        /// </summary>
        [JsonProperty(PropertyName = "ReservedInt2")]
        public int? ReservedInt2 { get; set; }

        /// <summary>
        /// Gets or sets the reserved int3.
        /// </summary>
        [JsonProperty(PropertyName = "ReservedInt3")]
        public int? ReservedInt3 { get; set; }

        /// <summary>
        /// Gets or sets the reserved int4.
        /// </summary>
        [JsonProperty(PropertyName = "ReservedInt4")]
        public int? ReservedInt4 { get; set; }

        /// <summary>
        /// Gets or sets the reserved string1.
        /// </summary>
        [JsonProperty(PropertyName = "ReservedString1")]
        public string ReservedString1 { get; set; }

        /// <summary>
        /// Gets or sets the reserved string2.
        /// </summary>
        [JsonProperty(PropertyName = "ReservedString2")]
        public string ReservedString2 { get; set; }

    }
}
