// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Softheon.Enterprise.Api.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Model for the GET Task input parameters
    /// </summary>
    public partial class GetTaskModel
    {
        /// <summary>
        /// Initializes a new instance of the GetTaskModel class.
        /// </summary>
        public GetTaskModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetTaskModel class.
        /// </summary>
        /// <param name="lastTaskID">Gets or sets the last task
        /// identifier.</param>
        /// <param name="id">Gets or sets the entity identifier.</param>
        /// <param name="type">Gets or sets the type of the entity.</param>
        /// <param name="queueID">Gets or sets the queue identifier.</param>
        /// <param name="queueType">Gets or sets the type of the queue.</param>
        /// <param name="drawerID">Gets or sets the drawer identifier.</param>
        /// <param name="description">Gets or sets the task
        /// description.</param>
        /// <param name="taskID">Gets or sets the task identifier.</param>
        /// <param name="page">Gets or sets the page number.</param>
        /// <param name="pageSize">Gets or sets the size of the page.</param>
        /// <param name="sortOrder">Gets or sets the order. Possible values
        /// include: 'Unspecified', 'Ascending', 'Descending'</param>
        /// <param name="sortBy">Gets or sets the column to order by. Possible
        /// values include: 'TaskID', 'QueueID', 'ObjectID', 'Priority',
        /// 'Description', 'InsertionTime', 'ResolutionTime',
        /// 'ReservedInt1'</param>
        public GetTaskModel(int? lastTaskID = default(int?), int? id = default(int?), int? type = default(int?), int? queueID = default(int?), int? queueType = default(int?), int? drawerID = default(int?), string description = default(string), int? taskID = default(int?), int? page = default(int?), int? pageSize = default(int?), string sortOrder = default(string), string sortBy = default(string))
        {
            LastTaskID = lastTaskID;
            ID = id;
            Type = type;
            QueueID = queueID;
            QueueType = queueType;
            DrawerID = drawerID;
            Description = description;
            TaskID = taskID;
            Page = page;
            PageSize = pageSize;
            SortOrder = sortOrder;
            SortBy = sortBy;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the last task identifier.
        /// </summary>
        [JsonProperty(PropertyName = "LastTaskID")]
        public int? LastTaskID { get; set; }

        /// <summary>
        /// Gets or sets the entity identifier.
        /// </summary>
        [JsonProperty(PropertyName = "ID")]
        public int? ID { get; set; }

        /// <summary>
        /// Gets or sets the type of the entity.
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public int? Type { get; set; }

        /// <summary>
        /// Gets or sets the queue identifier.
        /// </summary>
        [JsonProperty(PropertyName = "QueueID")]
        public int? QueueID { get; set; }

        /// <summary>
        /// Gets or sets the type of the queue.
        /// </summary>
        [JsonProperty(PropertyName = "QueueType")]
        public int? QueueType { get; set; }

        /// <summary>
        /// Gets or sets the drawer identifier.
        /// </summary>
        [JsonProperty(PropertyName = "DrawerID")]
        public int? DrawerID { get; set; }

        /// <summary>
        /// Gets or sets the task description.
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets the task identifier.
        /// </summary>
        [JsonProperty(PropertyName = "TaskID")]
        public int? TaskID { get; set; }

        /// <summary>
        /// Gets or sets the page number.
        /// </summary>
        [JsonProperty(PropertyName = "Page")]
        public int? Page { get; set; }

        /// <summary>
        /// Gets or sets the size of the page.
        /// </summary>
        [JsonProperty(PropertyName = "PageSize")]
        public int? PageSize { get; set; }

        /// <summary>
        /// Gets or sets the order. Possible values include: 'Unspecified',
        /// 'Ascending', 'Descending'
        /// </summary>
        [JsonProperty(PropertyName = "SortOrder")]
        public string SortOrder { get; set; }

        /// <summary>
        /// Gets or sets the column to order by. Possible values include:
        /// 'TaskID', 'QueueID', 'ObjectID', 'Priority', 'Description',
        /// 'InsertionTime', 'ResolutionTime', 'ReservedInt1'
        /// </summary>
        [JsonProperty(PropertyName = "SortBy")]
        public string SortBy { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (LastTaskID > 2147483647)
            {
                throw new ValidationException(ValidationRules.InclusiveMaximum, "LastTaskID", 2147483647);
            }
            if (LastTaskID < 0)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "LastTaskID", 0);
            }
            if (ID > 2147483647)
            {
                throw new ValidationException(ValidationRules.InclusiveMaximum, "ID", 2147483647);
            }
            if (ID < 1)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "ID", 1);
            }
            if (QueueType > 2147483647)
            {
                throw new ValidationException(ValidationRules.InclusiveMaximum, "QueueType", 2147483647);
            }
            if (QueueType < 1)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "QueueType", 1);
            }
            if (DrawerID > 2147483647)
            {
                throw new ValidationException(ValidationRules.InclusiveMaximum, "DrawerID", 2147483647);
            }
            if (DrawerID < 1)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "DrawerID", 1);
            }
            if (Description != null)
            {
                if (Description.Length > 255)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "Description", 255);
                }
                if (Description.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "Description", 0);
                }
            }
            if (Page > 2147483647)
            {
                throw new ValidationException(ValidationRules.InclusiveMaximum, "Page", 2147483647);
            }
            if (Page < 1)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "Page", 1);
            }
            if (PageSize > 1000)
            {
                throw new ValidationException(ValidationRules.InclusiveMaximum, "PageSize", 1000);
            }
            if (PageSize < 1)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "PageSize", 1);
            }
        }
    }
}
