// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Softheon.Enterprise.Api.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The model that is sent in response to a GET request for
    /// GroupsApplication associations
    /// </summary>
    public partial class GroupApplicationModel
    {
        /// <summary>
        /// Initializes a new instance of the GroupApplicationModel class.
        /// </summary>
        public GroupApplicationModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GroupApplicationModel class.
        /// </summary>
        /// <param name="groupID">Gets or sets the group identifier.</param>
        /// <param name="groupName">Gets or sets the name of the group.</param>
        /// <param name="applicationID">Gets or sets the application
        /// identifier.</param>
        /// <param name="applicationName">Gets or sets the name of the
        /// application.</param>
        /// <param name="acl">Gets or sets the acl.</param>
        public GroupApplicationModel(int? groupID = default(int?), string groupName = default(string), int? applicationID = default(int?), string applicationName = default(string), int? acl = default(int?))
        {
            GroupID = groupID;
            GroupName = groupName;
            ApplicationID = applicationID;
            ApplicationName = applicationName;
            Acl = acl;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the group identifier.
        /// </summary>
        [JsonProperty(PropertyName = "GroupID")]
        public int? GroupID { get; set; }

        /// <summary>
        /// Gets or sets the name of the group.
        /// </summary>
        [JsonProperty(PropertyName = "GroupName")]
        public string GroupName { get; set; }

        /// <summary>
        /// Gets or sets the application identifier.
        /// </summary>
        [JsonProperty(PropertyName = "ApplicationID")]
        public int? ApplicationID { get; set; }

        /// <summary>
        /// Gets or sets the name of the application.
        /// </summary>
        [JsonProperty(PropertyName = "ApplicationName")]
        public string ApplicationName { get; set; }

        /// <summary>
        /// Gets or sets the acl.
        /// </summary>
        [JsonProperty(PropertyName = "Acl")]
        public int? Acl { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (GroupName != null)
            {
                if (GroupName.Length > 255)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "GroupName", 255);
                }
                if (GroupName.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "GroupName", 0);
                }
            }
            if (ApplicationName != null)
            {
                if (ApplicationName.Length > 255)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "ApplicationName", 255);
                }
                if (ApplicationName.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "ApplicationName", 0);
                }
            }
        }
    }
}
