// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Softheon.Enterprise.Api.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The model that is sent in response to a GET request for GroupsDrawer
    /// associations
    /// </summary>
    public partial class GroupDrawerModel
    {
        /// <summary>
        /// Initializes a new instance of the GroupDrawerModel class.
        /// </summary>
        public GroupDrawerModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GroupDrawerModel class.
        /// </summary>
        /// <param name="groupID">Gets or sets the group identifier.</param>
        /// <param name="groupName">Gets or sets the name of the group.</param>
        /// <param name="drawerID">Gets or sets the drawer identifier.</param>
        /// <param name="drawerName">Gets or sets the name of the
        /// drawer.</param>
        /// <param name="acl">Gets or sets the access control level
        /// permissions.</param>
        public GroupDrawerModel(int? groupID = default(int?), string groupName = default(string), int? drawerID = default(int?), string drawerName = default(string), int? acl = default(int?))
        {
            GroupID = groupID;
            GroupName = groupName;
            DrawerID = drawerID;
            DrawerName = drawerName;
            Acl = acl;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the group identifier.
        /// </summary>
        [JsonProperty(PropertyName = "GroupID")]
        public int? GroupID { get; set; }

        /// <summary>
        /// Gets or sets the name of the group.
        /// </summary>
        [JsonProperty(PropertyName = "GroupName")]
        public string GroupName { get; set; }

        /// <summary>
        /// Gets or sets the drawer identifier.
        /// </summary>
        [JsonProperty(PropertyName = "DrawerID")]
        public int? DrawerID { get; set; }

        /// <summary>
        /// Gets or sets the name of the drawer.
        /// </summary>
        [JsonProperty(PropertyName = "DrawerName")]
        public string DrawerName { get; set; }

        /// <summary>
        /// Gets or sets the access control level permissions.
        /// </summary>
        [JsonProperty(PropertyName = "Acl")]
        public int? Acl { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (GroupName != null)
            {
                if (GroupName.Length > 255)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "GroupName", 255);
                }
                if (GroupName.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "GroupName", 0);
                }
            }
            if (DrawerName != null)
            {
                if (DrawerName.Length > 255)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "DrawerName", 255);
                }
                if (DrawerName.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "DrawerName", 0);
                }
            }
        }
    }
}
