// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Softheon.Enterprise.Api.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The model that is sent in response to a GET request for GroupsQueue
    /// associations
    /// </summary>
    public partial class GroupQueueModel
    {
        /// <summary>
        /// Initializes a new instance of the GroupQueueModel class.
        /// </summary>
        public GroupQueueModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GroupQueueModel class.
        /// </summary>
        /// <param name="groupID">Gets or sets the group identifier.</param>
        /// <param name="groupName">Gets or sets the name of the group.</param>
        /// <param name="queueID">Gets or sets the queue identifier.</param>
        /// <param name="queueName">Gets or sets the name of the queue.</param>
        /// <param name="acl">Gets or sets the access control level
        /// permissions.</param>
        public GroupQueueModel(int? groupID = default(int?), string groupName = default(string), int? queueID = default(int?), string queueName = default(string), int? acl = default(int?))
        {
            GroupID = groupID;
            GroupName = groupName;
            QueueID = queueID;
            QueueName = queueName;
            Acl = acl;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the group identifier.
        /// </summary>
        [JsonProperty(PropertyName = "GroupID")]
        public int? GroupID { get; set; }

        /// <summary>
        /// Gets or sets the name of the group.
        /// </summary>
        [JsonProperty(PropertyName = "GroupName")]
        public string GroupName { get; set; }

        /// <summary>
        /// Gets or sets the queue identifier.
        /// </summary>
        [JsonProperty(PropertyName = "QueueID")]
        public int? QueueID { get; set; }

        /// <summary>
        /// Gets or sets the name of the queue.
        /// </summary>
        [JsonProperty(PropertyName = "QueueName")]
        public string QueueName { get; set; }

        /// <summary>
        /// Gets or sets the access control level permissions.
        /// </summary>
        [JsonProperty(PropertyName = "Acl")]
        public int? Acl { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (GroupName != null)
            {
                if (GroupName.Length > 255)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "GroupName", 255);
                }
                if (GroupName.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "GroupName", 0);
                }
            }
            if (QueueName != null)
            {
                if (QueueName.Length > 255)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "QueueName", 255);
                }
                if (QueueName.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "QueueName", 0);
                }
            }
        }
    }
}
