// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Softheon.Enterprise.Api.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The model that is sent in response to a GET request for Notes
    /// </summary>
    public partial class NoteModel
    {
        /// <summary>
        /// Initializes a new instance of the NoteModel class.
        /// </summary>
        public NoteModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NoteModel class.
        /// </summary>
        /// <param name="id">Gets or sets the identifier.</param>
        /// <param name="drawerID">Gets or sets the drawer identifier.</param>
        /// <param name="entityID">Gets or sets the entity identifier.</param>
        /// <param name="ownerUserID">Gets or sets the owner user
        /// identifier.</param>
        /// <param name="ownerUserFullName">Gets or sets the full name of the
        /// owner user.</param>
        /// <param name="ownerGroupID">Gets or sets the owner group
        /// identifier.</param>
        /// <param name="ownerGroupName">Gets or sets the name of the owner
        /// group.</param>
        /// <param name="creatorUserID">Gets or sets the creator user
        /// identifier.</param>
        /// <param name="creatorUserFullName">Gets or sets the full name of the
        /// creator user.</param>
        /// <param name="modifierUserID">Gets or sets the modifier user
        /// identifier.</param>
        /// <param name="modifierUserFullName">Gets or sets the full name of
        /// the modifier user.</param>
        /// <param name="creationTime">Gets or sets the creation time.</param>
        /// <param name="modificationTime">Gets or sets the modification
        /// time.</param>
        /// <param name="parentID">Gets or sets the parent identifier.</param>
        /// <param name="acl">Gets or sets the acl.</param>
        /// <param name="name">Gets or sets the name.</param>
        /// <param name="note">Gets or sets the note.</param>
        public NoteModel(int? id = default(int?), int? drawerID = default(int?), int? entityID = default(int?), int? ownerUserID = default(int?), string ownerUserFullName = default(string), int? ownerGroupID = default(int?), string ownerGroupName = default(string), int? creatorUserID = default(int?), string creatorUserFullName = default(string), int? modifierUserID = default(int?), string modifierUserFullName = default(string), System.DateTime? creationTime = default(System.DateTime?), System.DateTime? modificationTime = default(System.DateTime?), int? parentID = default(int?), int? acl = default(int?), string name = default(string), string note = default(string))
        {
            ID = id;
            DrawerID = drawerID;
            EntityID = entityID;
            OwnerUserID = ownerUserID;
            OwnerUserFullName = ownerUserFullName;
            OwnerGroupID = ownerGroupID;
            OwnerGroupName = ownerGroupName;
            CreatorUserID = creatorUserID;
            CreatorUserFullName = creatorUserFullName;
            ModifierUserID = modifierUserID;
            ModifierUserFullName = modifierUserFullName;
            CreationTime = creationTime;
            ModificationTime = modificationTime;
            ParentID = parentID;
            Acl = acl;
            Name = name;
            Note = note;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the identifier.
        /// </summary>
        [JsonProperty(PropertyName = "ID")]
        public int? ID { get; set; }

        /// <summary>
        /// Gets or sets the drawer identifier.
        /// </summary>
        [JsonProperty(PropertyName = "DrawerID")]
        public int? DrawerID { get; set; }

        /// <summary>
        /// Gets or sets the entity identifier.
        /// </summary>
        [JsonProperty(PropertyName = "EntityID")]
        public int? EntityID { get; set; }

        /// <summary>
        /// Gets or sets the owner user identifier.
        /// </summary>
        [JsonProperty(PropertyName = "OwnerUserID")]
        public int? OwnerUserID { get; set; }

        /// <summary>
        /// Gets or sets the full name of the owner user.
        /// </summary>
        [JsonProperty(PropertyName = "OwnerUserFullName")]
        public string OwnerUserFullName { get; set; }

        /// <summary>
        /// Gets or sets the owner group identifier.
        /// </summary>
        [JsonProperty(PropertyName = "OwnerGroupID")]
        public int? OwnerGroupID { get; set; }

        /// <summary>
        /// Gets or sets the name of the owner group.
        /// </summary>
        [JsonProperty(PropertyName = "OwnerGroupName")]
        public string OwnerGroupName { get; set; }

        /// <summary>
        /// Gets or sets the creator user identifier.
        /// </summary>
        [JsonProperty(PropertyName = "CreatorUserID")]
        public int? CreatorUserID { get; set; }

        /// <summary>
        /// Gets or sets the full name of the creator user.
        /// </summary>
        [JsonProperty(PropertyName = "CreatorUserFullName")]
        public string CreatorUserFullName { get; set; }

        /// <summary>
        /// Gets or sets the modifier user identifier.
        /// </summary>
        [JsonProperty(PropertyName = "ModifierUserID")]
        public int? ModifierUserID { get; set; }

        /// <summary>
        /// Gets or sets the full name of the modifier user.
        /// </summary>
        [JsonProperty(PropertyName = "ModifierUserFullName")]
        public string ModifierUserFullName { get; set; }

        /// <summary>
        /// Gets or sets the creation time.
        /// </summary>
        [JsonProperty(PropertyName = "CreationTime")]
        public System.DateTime? CreationTime { get; set; }

        /// <summary>
        /// Gets or sets the modification time.
        /// </summary>
        [JsonProperty(PropertyName = "ModificationTime")]
        public System.DateTime? ModificationTime { get; set; }

        /// <summary>
        /// Gets or sets the parent identifier.
        /// </summary>
        [JsonProperty(PropertyName = "ParentID")]
        public int? ParentID { get; set; }

        /// <summary>
        /// Gets or sets the acl.
        /// </summary>
        [JsonProperty(PropertyName = "Acl")]
        public int? Acl { get; set; }

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the note.
        /// </summary>
        [JsonProperty(PropertyName = "Note")]
        public string Note { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name != null)
            {
                if (Name.Length > 255)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "Name", 255);
                }
                if (Name.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "Name", 0);
                }
            }
            if (Note != null)
            {
                if (Note.Length > 8000)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "Note", 8000);
                }
                if (Note.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "Note", 0);
                }
            }
        }
    }
}
