// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Softheon.Enterprise.Api.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The model that is sent in response to a GET request for UserQueue
    /// associations
    /// </summary>
    public partial class UserQueueModel
    {
        /// <summary>
        /// Initializes a new instance of the UserQueueModel class.
        /// </summary>
        public UserQueueModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UserQueueModel class.
        /// </summary>
        /// <param name="userID">Gets or sets the user identifier.</param>
        /// <param name="userFullName">Gets or sets the full name of the
        /// user.</param>
        /// <param name="queueID">Gets or sets the queue identifier.</param>
        /// <param name="queueName">Gets or sets the name of the queue.</param>
        /// <param name="acl">Gets or sets the access control level
        /// permissions.</param>
        public UserQueueModel(int? userID = default(int?), string userFullName = default(string), int? queueID = default(int?), string queueName = default(string), int? acl = default(int?))
        {
            UserID = userID;
            UserFullName = userFullName;
            QueueID = queueID;
            QueueName = queueName;
            Acl = acl;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the user identifier.
        /// </summary>
        [JsonProperty(PropertyName = "UserID")]
        public int? UserID { get; set; }

        /// <summary>
        /// Gets or sets the full name of the user.
        /// </summary>
        [JsonProperty(PropertyName = "UserFullName")]
        public string UserFullName { get; set; }

        /// <summary>
        /// Gets or sets the queue identifier.
        /// </summary>
        [JsonProperty(PropertyName = "QueueID")]
        public int? QueueID { get; set; }

        /// <summary>
        /// Gets or sets the name of the queue.
        /// </summary>
        [JsonProperty(PropertyName = "QueueName")]
        public string QueueName { get; set; }

        /// <summary>
        /// Gets or sets the access control level permissions.
        /// </summary>
        [JsonProperty(PropertyName = "Acl")]
        public int? Acl { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (UserFullName != null)
            {
                if (UserFullName.Length > 255)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "UserFullName", 255);
                }
                if (UserFullName.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "UserFullName", 0);
                }
            }
            if (QueueName != null)
            {
                if (QueueName.Length > 255)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "QueueName", 255);
                }
                if (QueueName.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "QueueName", 0);
                }
            }
        }
    }
}
