# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AttachmentVersionModel(Model):
    """Attachment Version Model.

    :param version: Gets or sets the indexed version value.
    :type version: int
    :param attachment_id: Gets or sets the attachment identifier.
    :type attachment_id: int
    :param name: Gets or sets the string.
    :type name: str
    :param creator_user_id: Gets or sets the creator identifier.
    :type creator_user_id: int
    :param accessor_user_id: Gets or sets the identifier of the user who
     accessed the attachment version.
    :type accessor_user_id: int
    :param access_time: Gets or sets the time the version was last accessed.
    :type access_time: datetime
    :param creation_time: Gets or sets the creation time of the attachment
     version.
    :type creation_time: datetime
    :param modification_time: Gets or sets the modification time of the
     attachment version.
    :type modification_time: datetime
    :param comment: Gets or sets the description comment of changes that were
     made.
    :type comment: str
    :param reserved_int1: Gets or sets the reserved int1.
    :type reserved_int1: int
    :param reserved_int2: Gets or sets the reserved int2.
    :type reserved_int2: int
    :param reserved_int3: Gets or sets the reserved int3.
    :type reserved_int3: int
    :param reserved_int4: Gets or sets the reserved int4.
    :type reserved_int4: int
    :param reserved_string1: Gets or sets the reserved string1.
    :type reserved_string1: str
    :param reserved_string2: Gets or sets the reserved string2.
    :type reserved_string2: str
    """

    _attribute_map = {
        'version': {'key': 'Version', 'type': 'int'},
        'attachment_id': {'key': 'AttachmentID', 'type': 'int'},
        'name': {'key': 'Name', 'type': 'str'},
        'creator_user_id': {'key': 'CreatorUserID', 'type': 'int'},
        'accessor_user_id': {'key': 'AccessorUserID', 'type': 'int'},
        'access_time': {'key': 'AccessTime', 'type': 'iso-8601'},
        'creation_time': {'key': 'CreationTime', 'type': 'iso-8601'},
        'modification_time': {'key': 'ModificationTime', 'type': 'iso-8601'},
        'comment': {'key': 'Comment', 'type': 'str'},
        'reserved_int1': {'key': 'ReservedInt1', 'type': 'int'},
        'reserved_int2': {'key': 'ReservedInt2', 'type': 'int'},
        'reserved_int3': {'key': 'ReservedInt3', 'type': 'int'},
        'reserved_int4': {'key': 'ReservedInt4', 'type': 'int'},
        'reserved_string1': {'key': 'ReservedString1', 'type': 'str'},
        'reserved_string2': {'key': 'ReservedString2', 'type': 'str'},
    }

    def __init__(self, version=None, attachment_id=None, name=None, creator_user_id=None, accessor_user_id=None, access_time=None, creation_time=None, modification_time=None, comment=None, reserved_int1=None, reserved_int2=None, reserved_int3=None, reserved_int4=None, reserved_string1=None, reserved_string2=None):
        super(AttachmentVersionModel, self).__init__()
        self.version = version
        self.attachment_id = attachment_id
        self.name = name
        self.creator_user_id = creator_user_id
        self.accessor_user_id = accessor_user_id
        self.access_time = access_time
        self.creation_time = creation_time
        self.modification_time = modification_time
        self.comment = comment
        self.reserved_int1 = reserved_int1
        self.reserved_int2 = reserved_int2
        self.reserved_int3 = reserved_int3
        self.reserved_int4 = reserved_int4
        self.reserved_string1 = reserved_string1
        self.reserved_string2 = reserved_string2
