# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class GetEntityLinkRequestModel(Model):
    """Model for the GET Link input parameters.

    :param child_entity_id: Gets or sets the child entity identifier.
    :type child_entity_id: int
    :param child_drawer_id: Gets or sets the child drawer identifier.
    :type child_drawer_id: int
    :param child_type: Gets or sets the type of the child.
    :type child_type: int
    :param acl: Gets or sets the access control list.
    :type acl: int
    :param entity_id: Gets or sets the entity identifier.
    :type entity_id: int
    :param drawer_id: Gets or sets the drawer identifier.
    :type drawer_id: int
    :param name: Gets or sets the name.
    :type name: str
    :param creator_user_id: Gets or sets the creator user identifier.
    :type creator_user_id: int
    :param modifier_user_id: Gets or sets the modifier user identifier.
    :type modifier_user_id: int
    :param min_insertion_time: Gets or sets the minimum insertion time.
    :type min_insertion_time: datetime
    :param max_insertion_time: Gets or sets the maximum insertion time.
    :type max_insertion_time: datetime
    :param min_modification_time: Gets or sets the minimum modification time.
    :type min_modification_time: datetime
    :param max_modification_time: Gets or sets the maximum modification time.
    :type max_modification_time: datetime
    :param page: Gets or sets the page number.
    :type page: int
    :param page_size: Gets or sets the size of the page.
    :type page_size: int
    :param sort_order: Gets or sets the order. Possible values include:
     'Unspecified', 'Ascending', 'Descending'
    :type sort_order: str or ~softheon.enterprise.api.client.models.enum
    :param sort_by: Gets or sets the column to order by. Possible values
     include: 'PageNumber', 'ID', 'Type', 'InsertionTime', 'ModificationTime',
     'CrossReferenceID', 'SubType', 'Extension', 'Name'
    :type sort_by: str or ~softheon.enterprise.api.client.models.enum
    """

    _validation = {
        'child_entity_id': {'maximum': 2147483647, 'minimum': 1},
        'child_drawer_id': {'maximum': 2147483647, 'minimum': 1},
        'child_type': {'maximum': 2147483647, 'minimum': 1},
        'entity_id': {'maximum': 2147483647, 'minimum': 1},
        'drawer_id': {'maximum': 2147483647, 'minimum': 1},
        'name': {'max_length': 255, 'min_length': 0},
        'creator_user_id': {'maximum': 2147483647, 'minimum': 1},
        'modifier_user_id': {'maximum': 2147483647, 'minimum': 1},
        'page': {'maximum': 2147483647, 'minimum': 1},
        'page_size': {'maximum': 1000, 'minimum': 1},
    }

    _attribute_map = {
        'child_entity_id': {'key': 'ChildEntityID', 'type': 'int'},
        'child_drawer_id': {'key': 'ChildDrawerID', 'type': 'int'},
        'child_type': {'key': 'ChildType', 'type': 'int'},
        'acl': {'key': 'Acl', 'type': 'int'},
        'entity_id': {'key': 'EntityID', 'type': 'int'},
        'drawer_id': {'key': 'DrawerID', 'type': 'int'},
        'name': {'key': 'Name', 'type': 'str'},
        'creator_user_id': {'key': 'CreatorUserID', 'type': 'int'},
        'modifier_user_id': {'key': 'ModifierUserID', 'type': 'int'},
        'min_insertion_time': {'key': 'MinInsertionTime', 'type': 'iso-8601'},
        'max_insertion_time': {'key': 'MaxInsertionTime', 'type': 'iso-8601'},
        'min_modification_time': {'key': 'MinModificationTime', 'type': 'iso-8601'},
        'max_modification_time': {'key': 'MaxModificationTime', 'type': 'iso-8601'},
        'page': {'key': 'Page', 'type': 'int'},
        'page_size': {'key': 'PageSize', 'type': 'int'},
        'sort_order': {'key': 'SortOrder', 'type': 'str'},
        'sort_by': {'key': 'SortBy', 'type': 'str'},
    }

    def __init__(self, child_entity_id=None, child_drawer_id=None, child_type=None, acl=None, entity_id=None, drawer_id=None, name=None, creator_user_id=None, modifier_user_id=None, min_insertion_time=None, max_insertion_time=None, min_modification_time=None, max_modification_time=None, page=None, page_size=None, sort_order=None, sort_by=None):
        super(GetEntityLinkRequestModel, self).__init__()
        self.child_entity_id = child_entity_id
        self.child_drawer_id = child_drawer_id
        self.child_type = child_type
        self.acl = acl
        self.entity_id = entity_id
        self.drawer_id = drawer_id
        self.name = name
        self.creator_user_id = creator_user_id
        self.modifier_user_id = modifier_user_id
        self.min_insertion_time = min_insertion_time
        self.max_insertion_time = max_insertion_time
        self.min_modification_time = min_modification_time
        self.max_modification_time = max_modification_time
        self.page = page
        self.page_size = page_size
        self.sort_order = sort_order
        self.sort_by = sort_by
