# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class GroupQueueModel(Model):
    """The model that is sent in response to a GET request for GroupsQueue
    associations.

    :param group_id: Gets or sets the group identifier.
    :type group_id: int
    :param group_name: Gets or sets the name of the group.
    :type group_name: str
    :param queue_id: Gets or sets the queue identifier.
    :type queue_id: int
    :param queue_name: Gets or sets the name of the queue.
    :type queue_name: str
    :param acl: Gets or sets the access control level permissions.
    :type acl: int
    """

    _validation = {
        'group_name': {'max_length': 255, 'min_length': 0},
        'queue_name': {'max_length': 255, 'min_length': 0},
    }

    _attribute_map = {
        'group_id': {'key': 'GroupID', 'type': 'int'},
        'group_name': {'key': 'GroupName', 'type': 'str'},
        'queue_id': {'key': 'QueueID', 'type': 'int'},
        'queue_name': {'key': 'QueueName', 'type': 'str'},
        'acl': {'key': 'Acl', 'type': 'int'},
    }

    def __init__(self, group_id=None, group_name=None, queue_id=None, queue_name=None, acl=None):
        super(GroupQueueModel, self).__init__()
        self.group_id = group_id
        self.group_name = group_name
        self.queue_id = queue_id
        self.queue_name = queue_name
        self.acl = acl
