# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class InsertQueueRequestModel(Model):
    """Model for POST Queue input parameters.

    :param name: Gets or sets the name.
    :type name: str
    :param alias: Gets or sets the alias.
    :type alias: str
    :param type: Gets or sets the type. Possible values include: 'Inbound',
     'Outbound', 'Access', 'Any', 'Shared', 'Public', 'Recycle', 'Fax',
     'Print', 'Scan', 'Ocr', 'Workflow', 'Schedule', 'System', 'Other',
     'CdoInfostore', 'CdoFolder'
    :type type: str or ~softheon.enterprise.api.client.models.enum
    """

    _validation = {
        'name': {'required': True, 'max_length': 255, 'min_length': 0},
        'alias': {'required': True, 'max_length': 255, 'min_length': 0},
        'type': {'required': True},
    }

    _attribute_map = {
        'name': {'key': 'Name', 'type': 'str'},
        'alias': {'key': 'Alias', 'type': 'str'},
        'type': {'key': 'Type', 'type': 'str'},
    }

    def __init__(self, name, alias, type):
        super(InsertQueueRequestModel, self).__init__()
        self.name = name
        self.alias = alias
        self.type = type
