# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class UpdateAttachmentRequestModel(Model):
    """Model for the PUT Attachment input parameters.

    :param category: Gets or sets the category.
    :type category: int
    :param class_property: Gets or sets the class.
    :type class_property: int
    :param name: Gets or sets the name.
    :type name: str
    :param acl: Gets or sets the acl.
    :type acl: int
    :param page_number: Gets or sets the page number.
    :type page_number: int
    :param state: Gets or sets the state. Possible values include:
     'Undefined', 'MaxStates', 'Reserved', 'UserDefined', 'Dynamic', 'Static',
     'New', 'CheckedOut', 'Internal', 'Statres5', 'Linked', 'Statres4',
     'Statres3', 'Statres2', 'Statres1', 'Locked', 'OnServerCache',
     'OnClientCache', 'Fetching', 'Dynres4', 'Dynres3', 'Dynres2', 'Dynres1',
     'User1', 'User2', 'User3', 'User4', 'User5', 'User6', 'User7', 'User8',
     'User9', 'User10', 'User11', 'User12', 'User13', 'User14', 'User15',
     'User16'
    :type state: str or ~softheon.enterprise.api.client.models.enum
    :param note: Gets or sets the note.
    :type note: str
    """

    _validation = {
        'name': {'max_length': 255, 'min_length': 0},
        'page_number': {'maximum': 2147483647, 'minimum': 0},
        'note': {'max_length': 255, 'min_length': 0},
    }

    _attribute_map = {
        'category': {'key': 'Category', 'type': 'int'},
        'class_property': {'key': 'Class', 'type': 'int'},
        'name': {'key': 'Name', 'type': 'str'},
        'acl': {'key': 'Acl', 'type': 'int'},
        'page_number': {'key': 'PageNumber', 'type': 'int'},
        'state': {'key': 'State', 'type': 'str'},
        'note': {'key': 'Note', 'type': 'str'},
    }

    def __init__(self, category=None, class_property=None, name=None, acl=None, page_number=None, state=None, note=None):
        super(UpdateAttachmentRequestModel, self).__init__()
        self.category = category
        self.class_property = class_property
        self.name = name
        self.acl = acl
        self.page_number = page_number
        self.state = state
        self.note = note
