# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class UserQueueModel(Model):
    """The model that is sent in response to a GET request for UserQueue
    associations.

    :param user_id: Gets or sets the user identifier.
    :type user_id: int
    :param user_full_name: Gets or sets the full name of the user.
    :type user_full_name: str
    :param queue_id: Gets or sets the queue identifier.
    :type queue_id: int
    :param queue_name: Gets or sets the name of the queue.
    :type queue_name: str
    :param acl: Gets or sets the access control level permissions.
    :type acl: int
    """

    _validation = {
        'user_full_name': {'max_length': 255, 'min_length': 0},
        'queue_name': {'max_length': 255, 'min_length': 0},
    }

    _attribute_map = {
        'user_id': {'key': 'UserID', 'type': 'int'},
        'user_full_name': {'key': 'UserFullName', 'type': 'str'},
        'queue_id': {'key': 'QueueID', 'type': 'int'},
        'queue_name': {'key': 'QueueName', 'type': 'str'},
        'acl': {'key': 'Acl', 'type': 'int'},
    }

    def __init__(self, user_id=None, user_full_name=None, queue_id=None, queue_name=None, acl=None):
        super(UserQueueModel, self).__init__()
        self.user_id = user_id
        self.user_full_name = user_full_name
        self.queue_id = queue_id
        self.queue_name = queue_name
        self.acl = acl
