/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Model for the GET Association input parameters
 *
 */
class GetAssociationRequestModel {
  /**
   * Create a GetAssociationRequestModel.
   * @member {number} [acl] Gets or sets the access control level permissions.
   * @member {number} [page] Gets or sets the page number.
   * @member {number} [pageSize] Gets or sets the size of the page.
   * @member {string} [sortOrder] Gets or sets the order. Possible values
   * include: 'Unspecified', 'Ascending', 'Descending'
   * @member {string} [sortBy] Gets or sets the column to order by. Possible
   * values include: 'Unspecified', 'DrawerID', 'ApplicationID', 'GroupID',
   * 'UserID', 'QueueID', 'Acl'
   */
  constructor() {
  }

  /**
   * Defines the metadata of GetAssociationRequestModel
   *
   * @returns {object} metadata of GetAssociationRequestModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'GetAssociationRequestModel',
      type: {
        name: 'Composite',
        className: 'GetAssociationRequestModel',
        modelProperties: {
          acl: {
            required: false,
            serializedName: 'Acl',
            type: {
              name: 'Number'
            }
          },
          page: {
            required: false,
            serializedName: 'Page',
            constraints: {
              InclusiveMaximum: 2147483647,
              InclusiveMinimum: 1
            },
            type: {
              name: 'Number'
            }
          },
          pageSize: {
            required: false,
            serializedName: 'PageSize',
            constraints: {
              InclusiveMaximum: 1000,
              InclusiveMinimum: 1
            },
            type: {
              name: 'Number'
            }
          },
          sortOrder: {
            required: false,
            serializedName: 'SortOrder',
            type: {
              name: 'String'
            }
          },
          sortBy: {
            required: false,
            serializedName: 'SortBy',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = GetAssociationRequestModel;
