/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Model for the GET Template input parameters
 *
 */
class GetDefinitionModel {
  /**
   * Create a GetDefinitionModel.
   * @member {number} [drawerID] Gets or sets the drawer identifier.
   * @member {string} [name] Gets or sets the name.
   * @member {string} [category] Gets or sets the category.
   * @member {number} [page] Gets or sets the page number.
   * @member {number} [pageSize] Gets or sets the size of the page.
   * @member {string} [sortOrder] Gets or sets the order. Possible values
   * include: 'Unspecified', 'Ascending', 'Descending'
   * @member {number} [sortBy] Gets or sets the column to order by.
   */
  constructor() {
  }

  /**
   * Defines the metadata of GetDefinitionModel
   *
   * @returns {object} metadata of GetDefinitionModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'GetDefinitionModel',
      type: {
        name: 'Composite',
        className: 'GetDefinitionModel',
        modelProperties: {
          drawerID: {
            required: false,
            serializedName: 'DrawerID',
            constraints: {
              InclusiveMaximum: 2147483647,
              InclusiveMinimum: 1
            },
            type: {
              name: 'Number'
            }
          },
          name: {
            required: false,
            serializedName: 'Name',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          category: {
            required: false,
            serializedName: 'Category',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          page: {
            required: false,
            serializedName: 'Page',
            constraints: {
              InclusiveMaximum: 2147483647,
              InclusiveMinimum: 1
            },
            type: {
              name: 'Number'
            }
          },
          pageSize: {
            required: false,
            serializedName: 'PageSize',
            constraints: {
              InclusiveMaximum: 1000,
              InclusiveMinimum: 1
            },
            type: {
              name: 'Number'
            }
          },
          sortOrder: {
            required: false,
            serializedName: 'SortOrder',
            type: {
              name: 'String'
            }
          },
          sortBy: {
            required: false,
            serializedName: 'SortBy',
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = GetDefinitionModel;
