/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Model for the GET Group input parameters
 *
 */
class GetGroupRequestModel {
  /**
   * Create a GetGroupRequestModel.
   * @member {number} [id] Gets or sets the group identifier.
   * @member {number} [userID] Gets or sets the user identifier.
   * @member {string} [name] Gets or sets the name.
   * @member {string} [type] Gets or sets the type. Possible values include:
   * 'Generic', 'Access', 'Role'
   * @member {string} [state] Gets or sets the state. Possible values include:
   * 'Inactive', 'Active'
   * @member {number} [page] Gets or sets the page number.
   * @member {number} [pageSize] Gets or sets the size of the page.
   * @member {string} [sortOrder] Gets or sets the order. Possible values
   * include: 'Unspecified', 'Ascending', 'Descending'
   * @member {string} [sortBy] Gets or sets the column to order by. Possible
   * values include: 'ID', 'Name', 'Type', 'State'
   */
  constructor() {
  }

  /**
   * Defines the metadata of GetGroupRequestModel
   *
   * @returns {object} metadata of GetGroupRequestModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'GetGroupRequestModel',
      type: {
        name: 'Composite',
        className: 'GetGroupRequestModel',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'ID',
            constraints: {
              InclusiveMaximum: 2147483647,
              InclusiveMinimum: 1
            },
            type: {
              name: 'Number'
            }
          },
          userID: {
            required: false,
            serializedName: 'UserID',
            constraints: {
              InclusiveMaximum: 2147483647,
              InclusiveMinimum: 1
            },
            type: {
              name: 'Number'
            }
          },
          name: {
            required: false,
            serializedName: 'Name',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          type: {
            required: false,
            serializedName: 'Type',
            type: {
              name: 'String'
            }
          },
          state: {
            required: false,
            serializedName: 'State',
            type: {
              name: 'String'
            }
          },
          page: {
            required: false,
            serializedName: 'Page',
            constraints: {
              InclusiveMaximum: 2147483647,
              InclusiveMinimum: 1
            },
            type: {
              name: 'Number'
            }
          },
          pageSize: {
            required: false,
            serializedName: 'PageSize',
            constraints: {
              InclusiveMaximum: 1000,
              InclusiveMinimum: 1
            },
            type: {
              name: 'Number'
            }
          },
          sortOrder: {
            required: false,
            serializedName: 'SortOrder',
            type: {
              name: 'String'
            }
          },
          sortBy: {
            required: false,
            serializedName: 'SortBy',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = GetGroupRequestModel;
