/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Model for the GET User input parameters
 *
 */
class GetUserRequestModel {
  /**
   * Create a GetUserRequestModel.
   * @member {number} [id] Gets or sets the identifier.
   * @member {number} [primaryGroupID] Gets or sets the primary group
   * identifier.
   * @member {number} [groupID] Gets or sets the group identifier.
   * @member {string} [groupName] Gets or sets the name of the group.
   * @member {string} [username] Gets or sets the username.
   * @member {string} [type] Gets or sets the type. Possible values include:
   * 'ImageDesk', 'PublishDesk', 'FaxDesk', 'CaptureDesk', 'RecognitionDesk',
   * 'PortalUser', 'AdminDesk', 'WorkflowDesk', 'Benchmark', 'ReportDesk',
   * 'ColdDesk', 'PortalDesk', 'WorkflowArchitect', 'DocumentDesk', 'Poweruser'
   * @member {string} [state] Gets or sets the state. Possible values include:
   * 'Active', 'Inactive'
   * @member {string} [fullName] Gets or sets the full name.
   * @member {number} [page] Gets or sets the page number.
   * @member {number} [pageSize] Gets or sets the size of the page.
   * @member {string} [sortOrder] Gets or sets the order. Possible values
   * include: 'Unspecified', 'Ascending', 'Descending'
   * @member {string} [sortBy] Gets or sets the column to order by. Possible
   * values include: 'ID', 'PrimaryGroupID', 'Username', 'UserFullName',
   * 'Type', 'State'
   */
  constructor() {
  }

  /**
   * Defines the metadata of GetUserRequestModel
   *
   * @returns {object} metadata of GetUserRequestModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'GetUserRequestModel',
      type: {
        name: 'Composite',
        className: 'GetUserRequestModel',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'ID',
            type: {
              name: 'Number'
            }
          },
          primaryGroupID: {
            required: false,
            serializedName: 'PrimaryGroupID',
            type: {
              name: 'Number'
            }
          },
          groupID: {
            required: false,
            serializedName: 'GroupID',
            type: {
              name: 'Number'
            }
          },
          groupName: {
            required: false,
            serializedName: 'GroupName',
            type: {
              name: 'String'
            }
          },
          username: {
            required: false,
            serializedName: 'Username',
            type: {
              name: 'String'
            }
          },
          type: {
            required: false,
            serializedName: 'Type',
            type: {
              name: 'String'
            }
          },
          state: {
            required: false,
            serializedName: 'State',
            type: {
              name: 'String'
            }
          },
          fullName: {
            required: false,
            serializedName: 'FullName',
            type: {
              name: 'String'
            }
          },
          page: {
            required: false,
            serializedName: 'Page',
            constraints: {
              InclusiveMaximum: 2147483647,
              InclusiveMinimum: 1
            },
            type: {
              name: 'Number'
            }
          },
          pageSize: {
            required: false,
            serializedName: 'PageSize',
            constraints: {
              InclusiveMaximum: 1000,
              InclusiveMinimum: 1
            },
            type: {
              name: 'Number'
            }
          },
          sortOrder: {
            required: false,
            serializedName: 'SortOrder',
            type: {
              name: 'String'
            }
          },
          sortBy: {
            required: false,
            serializedName: 'SortBy',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = GetUserRequestModel;
