/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The model that is sent in response to a GET request for GroupUser
 * associations
 *
 */
class GroupUserModel {
  /**
   * Create a GroupUserModel.
   * @member {number} [groupID] Gets or sets the group identifier.
   * @member {string} [groupName] Gets or sets the name of the group.
   * @member {number} [userID] Gets or sets the user identifier.
   * @member {string} [userFullName] Gets or sets the full name of the user.
   */
  constructor() {
  }

  /**
   * Defines the metadata of GroupUserModel
   *
   * @returns {object} metadata of GroupUserModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'GroupUserModel',
      type: {
        name: 'Composite',
        className: 'GroupUserModel',
        modelProperties: {
          groupID: {
            required: false,
            serializedName: 'GroupID',
            type: {
              name: 'Number'
            }
          },
          groupName: {
            required: false,
            serializedName: 'GroupName',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          userID: {
            required: false,
            serializedName: 'UserID',
            type: {
              name: 'Number'
            }
          },
          userFullName: {
            required: false,
            serializedName: 'UserFullName',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = GroupUserModel;
