/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Model for Template Profiles
 *
 */
class ProfileDefinitionModel {
  /**
   * Create a ProfileDefinitionModel.
   * @member {string} [id] Gets or sets the identifier.
   * @member {number} type Gets or sets the type.
   * @member {string} name Gets or sets the name.
   * @member {string} [reservedString1] Gets or sets the reserved string1.
   * @member {number} [reservedInt1] Gets or sets the reserved int1.
   * @member {array} [fields] Gets or sets the fields.
   */
  constructor() {
  }

  /**
   * Defines the metadata of ProfileDefinitionModel
   *
   * @returns {object} metadata of ProfileDefinitionModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ProfileDefinitionModel',
      type: {
        name: 'Composite',
        className: 'ProfileDefinitionModel',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'ID',
            type: {
              name: 'String'
            }
          },
          type: {
            required: true,
            serializedName: 'Type',
            constraints: {
              InclusiveMaximum: 2147483647,
              InclusiveMinimum: 1
            },
            type: {
              name: 'Number'
            }
          },
          name: {
            required: true,
            serializedName: 'Name',
            type: {
              name: 'String'
            }
          },
          reservedString1: {
            required: false,
            serializedName: 'ReservedString1',
            type: {
              name: 'String'
            }
          },
          reservedInt1: {
            required: false,
            serializedName: 'ReservedInt1',
            type: {
              name: 'Number'
            }
          },
          fields: {
            required: false,
            serializedName: 'Fields',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'FieldDefinitionModelElementType',
                  type: {
                    name: 'Composite',
                    className: 'FieldDefinitionModel'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = ProfileDefinitionModel;
