/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Model for PUT Queue parameters.
 *
 */
class QueueBase {
  /**
   * Create a QueueBase.
   * @member {string} [name] Gets or sets the name.
   * @member {string} [alias] Gets or sets the alias.
   * @member {string} [state] Gets or sets the state. Possible values include:
   * 'Inactive', 'Active'
   * @member {string} [type] Gets or sets the type. Possible values include:
   * 'Inbound', 'Outbound', 'Access', 'Any', 'Shared', 'Public', 'Recycle',
   * 'Fax', 'Print', 'Scan', 'Ocr', 'Workflow', 'Schedule', 'System', 'Other',
   * 'CdoInfostore', 'CdoFolder'
   * @member {string} [category] Gets or sets the category.
   * @member {string} [description] Gets or sets the description.
   * @member {number} [reservedInt1] Gets or sets the reserved integer 1.
   * @member {number} [reservedInt2] Gets or sets the reserved integer 2.
   * @member {string} [reservedString1] Gets or sets the reserved string 1.
   * @member {string} [reservedString2] Gets or sets the reserved string 2.
   */
  constructor() {
  }

  /**
   * Defines the metadata of QueueBase
   *
   * @returns {object} metadata of QueueBase
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'QueueBase',
      type: {
        name: 'Composite',
        className: 'QueueBase',
        modelProperties: {
          name: {
            required: false,
            serializedName: 'Name',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          alias: {
            required: false,
            serializedName: 'Alias',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          state: {
            required: false,
            serializedName: 'State',
            type: {
              name: 'String'
            }
          },
          type: {
            required: false,
            serializedName: 'Type',
            type: {
              name: 'String'
            }
          },
          category: {
            required: false,
            serializedName: 'Category',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          description: {
            required: false,
            serializedName: 'Description',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          reservedInt1: {
            required: false,
            serializedName: 'ReservedInt1',
            type: {
              name: 'Number'
            }
          },
          reservedInt2: {
            required: false,
            serializedName: 'ReservedInt2',
            type: {
              name: 'Number'
            }
          },
          reservedString1: {
            required: false,
            serializedName: 'ReservedString1',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          reservedString2: {
            required: false,
            serializedName: 'ReservedString2',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = QueueBase;
