/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The model that is sent in response to a GET request for Tasks
 *
 */
class TaskModel {
  /**
   * Create a TaskModel.
   * @member {number} [taskID] Gets or sets the task identifier.
   * @member {number} [queueID] Gets or sets the queue identifier.
   * @member {number} [drawerID] Gets or sets the drawer identifier.
   * @member {number} [objectID] Gets or sets the object identifier (entity).
   * @member {number} [objectType] Gets or sets the type of the object
   * (entity).
   * @member {number} [ownerUserID] Gets or sets the task owner user
   * identifier.
   * @member {string} [ownerUserFullName] Gets or sets the full name of the
   * owner user.
   * @member {number} [ownerGroupID] Gets or sets the task owner group
   * identifier.
   * @member {string} [ownerGroupName] Gets or sets the name of the owner
   * group.
   * @member {number} [effectiveUserID] Gets or sets the effective user
   * identifier.
   * @member {string} [effectiveUserFullName] Gets or sets the full name of the
   * effective user.
   * @member {number} [effectiveGroupID] Gets or sets the effective group
   * identifier.
   * @member {string} [effectiveGroupName] Gets or sets the name of the
   * effective group.
   * @member {number} [prevQueueID] Gets or sets the previous queue identifier.
   * @member {number} [nextQueueID] Gets or sets the next queue identifier.
   * @member {date} [insertionTime] Gets or sets the task insertion time.
   * @member {number} [addressID] Gets or sets the address identifier.
   * @member {string} [description] Gets or sets the description of the task.
   * @member {string} [message1] Gets or sets message 1.
   * @member {string} [message2] Gets or sets message 2.
   * @member {string} [message3] Gets or sets message 3.
   * @member {string} [message4] Gets or sets message 4.
   * @member {string} [message5] Gets or sets message5.
   * @member {string} [message6] Gets or sets message 6.
   * @member {string} [message7] Gets or sets message 7.
   * @member {string} [message8] Gets or sets message 8.
   * @member {string} [message9] Gets or sets message 9.
   * @member {string} [message10] Gets or sets message 10.
   * @member {string} [message11] Gets or sets message 11.
   * @member {string} [message12] Gets or sets message 12.
   * @member {string} [message13] Gets or sets message 13.
   * @member {string} [message14] Gets or sets message 14.
   * @member {string} [message15] Gets or sets message 15.
   * @member {string} [message16] Gets or sets message 16.
   * @member {number} [state] Gets or sets the task state.
   * @member {number} [priority] Gets or sets the task priority.
   * @member {date} [resolutionTime] Gets or sets the task resolution time.
   * @member {string} [taskFileAttachment] Gets or sets the task file
   * attachment name.
   * @member {number} [reservedInt1] Gets or sets reserved integer 1.
   * @member {string} [reservedString1] Gets or sets reserved string 1.
   */
  constructor() {
  }

  /**
   * Defines the metadata of TaskModel
   *
   * @returns {object} metadata of TaskModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'TaskModel',
      type: {
        name: 'Composite',
        className: 'TaskModel',
        modelProperties: {
          taskID: {
            required: false,
            serializedName: 'TaskID',
            type: {
              name: 'Number'
            }
          },
          queueID: {
            required: false,
            serializedName: 'QueueID',
            type: {
              name: 'Number'
            }
          },
          drawerID: {
            required: false,
            serializedName: 'DrawerID',
            type: {
              name: 'Number'
            }
          },
          objectID: {
            required: false,
            serializedName: 'ObjectID',
            type: {
              name: 'Number'
            }
          },
          objectType: {
            required: false,
            serializedName: 'ObjectType',
            type: {
              name: 'Number'
            }
          },
          ownerUserID: {
            required: false,
            serializedName: 'OwnerUserID',
            type: {
              name: 'Number'
            }
          },
          ownerUserFullName: {
            required: false,
            serializedName: 'OwnerUserFullName',
            type: {
              name: 'String'
            }
          },
          ownerGroupID: {
            required: false,
            serializedName: 'OwnerGroupID',
            type: {
              name: 'Number'
            }
          },
          ownerGroupName: {
            required: false,
            serializedName: 'OwnerGroupName',
            type: {
              name: 'String'
            }
          },
          effectiveUserID: {
            required: false,
            serializedName: 'EffectiveUserID',
            type: {
              name: 'Number'
            }
          },
          effectiveUserFullName: {
            required: false,
            serializedName: 'EffectiveUserFullName',
            type: {
              name: 'String'
            }
          },
          effectiveGroupID: {
            required: false,
            serializedName: 'EffectiveGroupID',
            type: {
              name: 'Number'
            }
          },
          effectiveGroupName: {
            required: false,
            serializedName: 'EffectiveGroupName',
            type: {
              name: 'String'
            }
          },
          prevQueueID: {
            required: false,
            serializedName: 'PrevQueueID',
            type: {
              name: 'Number'
            }
          },
          nextQueueID: {
            required: false,
            serializedName: 'NextQueueID',
            type: {
              name: 'Number'
            }
          },
          insertionTime: {
            required: false,
            serializedName: 'InsertionTime',
            type: {
              name: 'DateTime'
            }
          },
          addressID: {
            required: false,
            serializedName: 'AddressID',
            constraints: {
              InclusiveMaximum: 2147483647,
              InclusiveMinimum: 0
            },
            type: {
              name: 'Number'
            }
          },
          description: {
            required: false,
            serializedName: 'Description',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          message1: {
            required: false,
            serializedName: 'Message1',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          message2: {
            required: false,
            serializedName: 'Message2',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          message3: {
            required: false,
            serializedName: 'Message3',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          message4: {
            required: false,
            serializedName: 'Message4',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          message5: {
            required: false,
            serializedName: 'Message5',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          message6: {
            required: false,
            serializedName: 'Message6',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          message7: {
            required: false,
            serializedName: 'Message7',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          message8: {
            required: false,
            serializedName: 'Message8',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          message9: {
            required: false,
            serializedName: 'Message9',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          message10: {
            required: false,
            serializedName: 'Message10',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          message11: {
            required: false,
            serializedName: 'Message11',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          message12: {
            required: false,
            serializedName: 'Message12',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          message13: {
            required: false,
            serializedName: 'Message13',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          message14: {
            required: false,
            serializedName: 'Message14',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          message15: {
            required: false,
            serializedName: 'Message15',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          message16: {
            required: false,
            serializedName: 'Message16',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          state: {
            required: false,
            serializedName: 'State',
            type: {
              name: 'Number'
            }
          },
          priority: {
            required: false,
            serializedName: 'Priority',
            type: {
              name: 'Number'
            }
          },
          resolutionTime: {
            required: false,
            serializedName: 'ResolutionTime',
            type: {
              name: 'DateTime'
            }
          },
          taskFileAttachment: {
            required: false,
            serializedName: 'TaskFileAttachment',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          reservedInt1: {
            required: false,
            serializedName: 'ReservedInt1',
            type: {
              name: 'Number'
            }
          },
          reservedString1: {
            required: false,
            serializedName: 'ReservedString1',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = TaskModel;
