/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The model for PUT EntityLink input parameters.
 *
 */
class UpdateEntityLinkRequestModel {
  /**
   * Create a UpdateEntityLinkRequestModel.
   * @member {string} [virtualName] Gets or sets the name of the virtual.
   * @member {number} [classProperty] Gets or sets the class.
   * @member {string} [name] Gets or sets the name.
   * @member {number} [acl] Gets or sets the acl.
   * @member {number} [pageNumber] Gets or sets the page number.
   * @member {string} [state] Gets or sets the state. Possible values include:
   * 'Undefined', 'MaxStates', 'Reserved', 'UserDefined', 'Dynamic', 'Static',
   * 'New', 'CheckedOut', 'Internal', 'Statres5', 'Linked', 'Statres4',
   * 'Statres3', 'Statres2', 'Statres1', 'Locked', 'OnServerCache',
   * 'OnClientCache', 'Fetching', 'Dynres4', 'Dynres3', 'Dynres2', 'Dynres1',
   * 'User1', 'User2', 'User3', 'User4', 'User5', 'User6', 'User7', 'User8',
   * 'User9', 'User10', 'User11', 'User12', 'User13', 'User14', 'User15',
   * 'User16'
   * @member {string} [note] Gets or sets the note.
   */
  constructor() {
  }

  /**
   * Defines the metadata of UpdateEntityLinkRequestModel
   *
   * @returns {object} metadata of UpdateEntityLinkRequestModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'UpdateEntityLinkRequestModel',
      type: {
        name: 'Composite',
        className: 'UpdateEntityLinkRequestModel',
        modelProperties: {
          virtualName: {
            required: false,
            serializedName: 'VirtualName',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          classProperty: {
            required: false,
            serializedName: 'Class',
            type: {
              name: 'Number'
            }
          },
          name: {
            required: false,
            serializedName: 'Name',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          acl: {
            required: false,
            serializedName: 'Acl',
            type: {
              name: 'Number'
            }
          },
          pageNumber: {
            required: false,
            serializedName: 'PageNumber',
            constraints: {
              InclusiveMaximum: 2147483647,
              InclusiveMinimum: 0
            },
            type: {
              name: 'Number'
            }
          },
          state: {
            required: false,
            serializedName: 'State',
            type: {
              name: 'String'
            }
          },
          note: {
            required: false,
            serializedName: 'Note',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = UpdateEntityLinkRequestModel;
