/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * The Entity template update class.
 *
 */
class UpdateEntityDefinitionRequestModel {
  /**
   * Create a UpdateEntityDefinitionRequestModel.
   * @member {string} [category] Gets or sets the category of template.
   * @member {string} [name] Gets or sets the name of templates.
   * @member {string} [smallImage] Gets or sets the small image.
   * @member {string} [largeImage] Gets or sets the large image.
   * @member {boolean} [hasAudit] Gets or sets if the template has auditing
   * enabled.
   * @member {boolean} [allowsViewImages] Gets or sets if the template allows
   * viewing images.
   * @member {boolean} [isReviewState] Gets or sets if the entity is created in
   * a review state.
   * @member {array} [profiles] Gets or sets the profiles.
   */
  constructor() {
  }

  /**
   * Defines the metadata of UpdateEntityDefinitionRequestModel
   *
   * @returns {object} metadata of UpdateEntityDefinitionRequestModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'UpdateEntityDefinitionRequestModel',
      type: {
        name: 'Composite',
        className: 'UpdateEntityDefinitionRequestModel',
        modelProperties: {
          category: {
            required: false,
            serializedName: 'Category',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            serializedName: 'Name',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          smallImage: {
            required: false,
            serializedName: 'SmallImage',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          largeImage: {
            required: false,
            serializedName: 'LargeImage',
            constraints: {
              MaxLength: 255,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          hasAudit: {
            required: false,
            serializedName: 'HasAudit',
            type: {
              name: 'Boolean'
            }
          },
          allowsViewImages: {
            required: false,
            serializedName: 'AllowsViewImages',
            type: {
              name: 'Boolean'
            }
          },
          isReviewState: {
            required: false,
            serializedName: 'IsReviewState',
            type: {
              name: 'Boolean'
            }
          },
          profiles: {
            required: false,
            serializedName: 'Profiles',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ProfileDefinitionModelElementType',
                  type: {
                    name: 'Composite',
                    className: 'ProfileDefinitionModel'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = UpdateEntityDefinitionRequestModel;
